"""Stub for pyulog.px4 (PX4-specific ULog helpers)."""

from typing import Any, List, Optional

class PX4ULog:
    """PX4-specific ULog helpers (field names, MAV type, etc.)."""

    def __init__(self, ulog_object: Any) -> None: ...
    def get_mav_type(self) -> str: ...
    def get_estimator(self) -> str: ...
    def add_roll_pitch_yaw(self, messages: Optional[List[str]] = None) -> None: ...
    def get_configured_rc_input_names(self, channel: int) -> Optional[List[str]]: ...
