version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
  - package-ecosystem: "gomod"
    directory: "/go/cli/mcap/"
    schedule:
      interval: "daily"
    allow:
      - dependency-name: "github.com/foxglove/*"
