excluded:
  - .build

disabled_rules:
  - blanket_disable_command
  - function_body_length
  - type_body_length
  - file_length
  - cyclomatic_complexity

trailing_comma:
  mandatory_comma: true

identifier_name:
  excluded:
    - op
    - id
