site_name: "MCAP"
theme:
  name: material
  favicon: img/favicon32.png
  logo: img/mcap.png
  palette:
    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
      primary: "deep purple"
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
      primary: "deep purple"

  features:
    - navigation.tabs

use_directory_urls: false

nav:
  - Home: "index.md"
  - Documentation:
      - Specification:
          - "specification/README.md"
          - "specification/explanatory-notes.md"
          - "specification/appendix.md"
      - Motivation:
          - "motivation/evaluation-of-robotics-data-recording-file-formats.md"
      - Library Support: "support-matrix.md"
  - Guides:
      - Getting Started:
          - "guides/getting-started/index.md"
          - "guides/getting-started/converting-from-ros1.md"
          - "guides/getting-started/converting-from-ros2.md"
          - "guides/getting-started/reading-and-writing-mcap.md"
      - Python:
          - "guides/python/reading-writing-ros1.md"
          - "guides/python/reading-writing-ros2.md"
          - "guides/python/writing-jsonschema.md"
          - "guides/python/reading-writing-protobuf.md"
      - C++:
          - "guides/cpp/writing-protobuf.md"
      - Integrations:
          - "guides/integrations/visualize-in-foxglove-studio.md"

  - API: "api-docs.md"

markdown_extensions:
  - footnotes
  - admonition
  - pymdownx.highlight:
      use_pygments: true
  - pymdownx.superfences

repo_url: https://github.com/foxglove/mcap

extra:
  social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/foxglove
      name: Twitter
    - icon: fontawesome/brands/slack
      link: https://foxglovedev.slack.com
      name: Slack
    - icon: fontawesome/brands/github
      link: https://github.com/foxglove/mcap
      name: GitHub

copyright: Copyright &copy; 2022 Foxglove
