site_name: "MCAP"
theme:
  name: material
  favicon: img/favicon32.png
  logo: img/mcap.png
  palette:
    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
      primary: "black"
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
      primary: "white"
  font:
    text: Open Sans

use_directory_urls: false

nav:
  - Home:
      - "index.md"
      - "home/messages-channels-and-schemas.md"
      - "home/data-serialization-formats.md"
  - Getting Started:
      - "getting-started/overview.md"
      - "getting-started/ros-1.md"
      - "getting-started/ros-2.md"
      - "getting-started/protobuf.md"
      - "getting-started/json.md"
      - "getting-started/visualize-in-foxglove-studio.md"
  - Guides:
      - Python:
          - "guides/python/reading-writing-ros1.md"
          - "guides/python/reading-writing-ros2.md"
          - "guides/python/writing-jsonschema.md"
          - "guides/python/reading-writing-protobuf.md"
      - C++:
          - "guides/cpp/writing-protobuf.md"
  - API Reference:
      - Python: docs/python/index.html
      - C++: docs/cpp/index.html
      - Typescript: docs/typescript/index.html
      - Go: https://pkg.go.dev/github.com/foxglove/mcap/go/mcap
      - Swift: docs/swift/documentation/mcap/

  - More Resources:
      - GitHub: "https://github.com/foxglove/mcap"
      - mcap CLI: "https://github.com/foxglove/mcap/tree/main/go/cli/mcap"
      - Slack: "https://foxglovedev.slack.com"
      - Library Support: "support-matrix.md"
      - ROS 2 Storage Plugin: "https://github.com/ros-tooling/rosbag2_storage_mcap"
      - Specification:
          - "specification/README.md"
          - "specification/explanatory-notes.md"
          - "specification/appendix.md"
      - Motivation:
          - "motivation/evaluation-of-robotics-data-recording-file-formats.md"

markdown_extensions:
  - footnotes
  - admonition
  - pymdownx.highlight:
      use_pygments: true
  - pymdownx.superfences
  - mdx_truly_sane_lists

repo_url: https://github.com/foxglove/mcap

extra:
  social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/foxglovedev
      name: Twitter
    - icon: fontawesome/brands/slack
      link: https://foxglovedev.slack.com
      name: Slack
    - icon: fontawesome/brands/github
      link: https://github.com/foxglove/mcap
      name: GitHub

copyright: Copyright &copy; 2022 Foxglove
