# Configuration for all pages
site_name: "MCAP"
site_url: https://mcap.dev/
site_description: >-
  MCAP is a modular, performant, and serialization-agnostic container file format for pub/sub
  messages, primarily intended for use in robotics applications.
theme:
  name: material
  custom_dir: "docs/theme"
  favicon: img/favicon32.png
  logo: img/mcap240.webp
  icon:
    repo: fontawesome/brands/github
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
      primary: "white"
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
      primary: "black"
  font: false # Fonts are configured in theme/main.html

plugins:
  - social
  - glightbox

extra_css: [styles/extra.css]

markdown_extensions:
  - footnotes
  - admonition
  - pymdownx.highlight:
      use_pygments: true
  - pymdownx.superfences
  - mdx_truly_sane_lists
  - smarty

# links go directly to `.html` URL paths, this means we can preview the site in a GCS bucket.
use_directory_urls: false

# Site Layout
nav:
  - Home:
      - Introduction: "index.md"
      - "home/messages-channels-and-schemas.md"
      - "home/data-serialization-formats.md"
  - Getting Started:
      - "getting-started/overview.md"
      - "getting-started/ros-1.md"
      - "getting-started/ros-2.md"
      - "getting-started/protobuf.md"
      - "getting-started/json.md"
  - Guides:
      - Python:
          - "guides/python/ros1.md"
          - "guides/python/ros2.md"
          - "guides/python/json.md"
          - "guides/python/protobuf.md"
      - C++:
          - "guides/cpp/protobuf.md"
  - Specification:
      - "specification/README.md"
      - "specification/explanatory-notes.md"
      - "specification/appendix.md"
  - API Reference:
      - Python: docs/python/index.html
      - C++: docs/cpp/index.html
      - TypeScript: docs/typescript/index.html
      - Go: https://pkg.go.dev/github.com/foxglove/mcap/go/mcap
      - Swift: docs/swift/documentation/mcap/
      - Rust: docs/rust/mcap/index.html

  - More Resources:
      - GitHub: "https://github.com/foxglove/mcap"
      - mcap CLI: "https://github.com/foxglove/mcap/tree/main/go/cli/mcap"
      - Slack: "https://foxglovedev.slack.com"
      - Library Support: "support-matrix.md"
      - ROS 2 Storage Plugin: "https://github.com/ros-tooling/rosbag2_storage_mcap"
      - Motivation:
          - "motivation/evaluation-of-robotics-data-recording-file-formats.md"
      - Performance Evaluation: "performance-comparison/rosbag2-plugin-comparison.md"

# Header / Footer links and copy
repo_url: https://github.com/foxglove/mcap
edit_uri: "edit/main/docs/"

extra:
  analytics:
    provider: fathom
  social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/foxglovedev
      name: Twitter
    - icon: fontawesome/brands/slack
      link: https://foxglovedev.slack.com
      name: Slack
    - icon: fontawesome/brands/github
      link: https://github.com/foxglove/mcap
      name: GitHub

copyright: Copyright &copy; 2022 Foxglove
