site_name: "MCAP"
theme:
  name: material
  favicon: img/favicon32.png
  logo: img/mcap.png
  palette:
    # Palette toggle for dark mode
    scheme: slate
    primary: "deep purple"
  features:
    - navigation.tabs

use_directory_urls: false

nav:
  - Home: "index.md"
  - Documentation:
      - Specification:
          - "specification/README.md"
          - "specification/explanatory-notes.md"
          - "specification/appendix.md"
      - Motivation:
          - "motivation/evaluation-of-robotics-data-recording-file-formats.md"
      - Library Support: "support-matrix.md"
  - Guides:
      - "Guides/getting-started.md"
  - API Documentation:
      - Python: docs/python
      - C++: docs/cpp
      - Typescript: docs/typescript
      - Go: "https://pkg.go.dev/github.com/foxglove/mcap/go/mcap"
      - Swift: docs/swift/documentation/mcap

markdown_extensions:
  - pymdownx.snippets
  - footnotes
  - admonition

repo_url: https://github.com/foxglove/mcap
