# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: Log.proto
# Protobuf Python Version: 6.33.4
"""Generated protocol buffer code."""

from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC, 6, 33, 4, "", "Log.proto"
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\tLog.proto\x12\x08\x66oxglove"!\n\x04Time\x12\x0b\n\x03sec\x18\x01 \x01(\x07\x12\x0c\n\x04nsec\x18\x02 \x01(\x07"\xd5\x01\n\x03Log\x12!\n\ttimestamp\x18\x01 \x01(\x0b\x32\x0e.foxglove.Time\x12"\n\x05level\x18\x02 \x01(\x0e\x32\x13.foxglove.Log.Level\x12\x0f\n\x07message\x18\x03 \x01(\t\x12\x0c\n\x04name\x18\x04 \x01(\t\x12\x0c\n\x04\x66ile\x18\x05 \x01(\t\x12\x0c\n\x04line\x18\x06 \x01(\x07"L\n\x05Level\x12\x0b\n\x07UNKNOWN\x10\x00\x12\t\n\x05\x44\x45\x42UG\x10\x01\x12\x08\n\x04INFO\x10\x02\x12\x0b\n\x07WARNING\x10\x03\x12\t\n\x05\x45RROR\x10\x04\x12\t\n\x05\x46\x41TAL\x10\x05\x62\x06proto3'  # noqa: E501
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "Log_pb2", _globals)
if not _descriptor._USE_C_DESCRIPTORS:
    DESCRIPTOR._loaded_options = None
    _globals["_TIME"]._serialized_start = 23
    _globals["_TIME"]._serialized_end = 56
    _globals["_LOG"]._serialized_start = 59
    _globals["_LOG"]._serialized_end = 272
    _globals["_LOG_LEVEL"]._serialized_start = 196
    _globals["_LOG_LEVEL"]._serialized_end = 272
# @@protoc_insertion_point(module_scope)
