name: Set up Swift
description: Install Swift using Swiftly
inputs:
  swift-version:
    description: Version to install
    required: true
runs:
  using: composite
  steps:
    - run: curl -O https://download.swift.org/swiftly/linux/swiftly-1.0.0-x86_64.tar.gz
      shell: bash
    - run: echo "8c11f8bdeee212ed4b541a1ce2708866d4d290fdfe02362b0048b4cc57614341 swiftly-1.0.0-x86_64.tar.gz" | sha256sum --check --strict
      shell: bash
    - run: tar -zxf swiftly-1.0.0-x86_64.tar.gz
      shell: bash
    - run: ./swiftly init --skip-install
      shell: bash
    - run: ./swiftly install --use ${{ inputs.swift-version }}
      shell: bash
    - run: which swift
      shell: bash
    - run: swift --version
      shell: bash
    - run: "false"
      shell: bash
