# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: test_proto/complex_message.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from test_proto import intermediate_message_1_pb2 as test__proto_dot_intermediate__message__1__pb2
from test_proto import intermediate_message_2_pb2 as test__proto_dot_intermediate__message__2__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n test_proto/complex_message.proto\x12\ntest_proto\x1a\'test_proto/intermediate_message_1.proto\x1a\'test_proto/intermediate_message_2.proto\"\x82\x01\n\x0e\x43omplexMessage\x12\x37\n\rintermediate1\x18\x01 \x01(\x0b\x32 .test_proto.IntermediateMessage1\x12\x37\n\rintermediate2\x18\x02 \x01(\x0b\x32 .test_proto.IntermediateMessage2b\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'test_proto.complex_message_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _COMPLEXMESSAGE._serialized_start=131
  _COMPLEXMESSAGE._serialized_end=261
# @@protoc_insertion_point(module_scope)
