# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: test_proto/intermediate_message_2.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from test_proto import simple_message_pb2 as test__proto_dot_simple__message__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\'test_proto/intermediate_message_2.proto\x12\ntest_proto\x1a\x1ftest_proto/simple_message.proto\"A\n\x14IntermediateMessage2\x12)\n\x06simple\x18\x01 \x01(\x0b\x32\x19.test_proto.SimpleMessageb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'test_proto.intermediate_message_2_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _INTERMEDIATEMESSAGE2._serialized_start=88
  _INTERMEDIATEMESSAGE2._serialized_end=153
# @@protoc_insertion_point(module_scope)
