# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: test_proto/nested_type_message.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n$test_proto/nested_type_message.proto\x12\ntest_proto\"\xd6\x02\n\x11NestedTypeMessage\x12H\n\x15nested_type_message_1\x18\x01 \x01(\x0b\x32).test_proto.NestedTypeMessage.NestedType1\x12H\n\x15nested_type_message_2\x18\x02 \x01(\x0b\x32).test_proto.NestedTypeMessage.NestedType2\x1a\x8f\x01\n\x0bNestedType1\x12^\n\x1a\x64oubly_nested_type_message\x18\x01 \x01(\x0b\x32:.test_proto.NestedTypeMessage.NestedType1.DoublyNestedType\x1a \n\x10\x44oublyNestedType\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\t\x1a\x1b\n\x0bNestedType2\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\tb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'test_proto.nested_type_message_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _NESTEDTYPEMESSAGE._serialized_start=53
  _NESTEDTYPEMESSAGE._serialized_end=395
  _NESTEDTYPEMESSAGE_NESTEDTYPE1._serialized_start=223
  _NESTEDTYPEMESSAGE_NESTEDTYPE1._serialized_end=366
  _NESTEDTYPEMESSAGE_NESTEDTYPE1_DOUBLYNESTEDTYPE._serialized_start=334
  _NESTEDTYPEMESSAGE_NESTEDTYPE1_DOUBLYNESTEDTYPE._serialized_end=366
  _NESTEDTYPEMESSAGE_NESTEDTYPE2._serialized_start=368
  _NESTEDTYPEMESSAGE_NESTEDTYPE2._serialized_end=395
# @@protoc_insertion_point(module_scope)
