/* cspell:words dedup flamegraph lz4 multitopic ndjson noetic notashell notbag pprof samply testdata undercount undercounting undercounts */

import type { CliTestCase } from "./types.ts";

// These fixtures are generated by `yarn test:conformance:generate-inputs`.
// The suffixes encode the record/index features included in each generated file.
const ONE_MESSAGE = "{dataDir}/OneMessage/OneMessage-ch-chx-mx-pad-rch-rsh-st-sum.mcap";
// Unchunked, unindexed single-message file (no chunk index, no message index). Used to cover
// the Go-vs-Rust difference in how `cat` handles on-disk inputs without an index.
const ONE_MESSAGE_UNINDEXED = "{dataDir}/OneMessage/OneMessage.mcap";
const ONE_SCHEMALESS =
  "{dataDir}/OneSchemalessMessage/OneSchemalessMessage-ch-chx-mx-pad-rch-st.mcap";
const TEN_MESSAGES = "{dataDir}/TenMessages/TenMessages-ch-chx-mx-pad-rch-rsh-st-sum.mcap";
const ONE_ATTACHMENT = "{dataDir}/OneAttachment/OneAttachment-ax-st-sum.mcap";
// 8-byte magic + 1-byte header opcode + 8-byte header length + two empty MCAP strings.
const ONE_ATTACHMENT_RECORD_OFFSET = "25";
const ONE_METADATA = "{dataDir}/OneMetadata/OneMetadata-mdx-st-sum.mcap";
const ROS2_EMBEDDED_SCHEMA_DB3 = "{repoRoot}/testdata/db3/talker-iron.db3";
// A committed MCAP whose statistics carry a real wall-clock (2017, above the info date cutoff) so
// `info` renders an absolute RFC3339 start/end. Reused read-only from the mcap crate's test data.
const WALL_CLOCK_MCAP = "{repoRoot}/rust/mcap/tests/data/uncompressed.mcap";
const NOETIC_MULTITOPIC_NONE = "{repoRoot}/testdata/bags/generated/noetic-multitopic-none.bag";
const NOETIC_MULTITOPIC_BZ2 = "{repoRoot}/testdata/bags/generated/noetic-multitopic-bz2.bag";
const NOETIC_MULTITOPIC_LZ4 = "{repoRoot}/testdata/bags/generated/noetic-multitopic-lz4.bag";

const HELP_PATHS = [
  ["add"],
  ["add", "attachment"],
  ["add", "metadata"],
  ["cat"],
  ["compress"],
  ["convert"],
  ["decompress"],
  ["doctor"],
  ["du"],
  ["filter"],
  ["get"],
  ["get", "attachment"],
  ["get", "metadata"],
  ["info"],
  ["list"],
  ["list", "attachments"],
  ["list", "channels"],
  ["list", "chunks"],
  ["list", "metadata"],
  ["list", "schemas"],
  ["merge"],
  ["recover"],
  ["sort"],
] as const;

const EXIT_CODE_ONLY = {
  exitCode: 0,
  stdout: { kind: "ignore" },
  stderr: { kind: "ignore" },
} as const;

const HELP_EXISTS = {
  exitCode: 0,
  stdout: { kind: "nonempty" },
  stderr: { kind: "ignore" },
} as const;

export const cases: CliTestCase[] = [
  {
    id: "root-help-command-list",
    description:
      "Root help advertises the same supported command list, ignoring the Go-only version subcommand.",
    tags: ["surface", "help"],
    invocation: { args: ["--help"] },
    comparison: {
      exitCode: 0,
      stdout: { kind: "command-list", ignoreCommands: ["version"] },
      stderr: { kind: "text" },
    },
  },
  ...HELP_PATHS.map<CliTestCase>((args) => ({
    id: `command-help-${args.join("-")}`,
    description: `Both CLIs expose help for '${args.join(" ")}'.`,
    tags: ["surface", "help"],
    invocation: { args: [...args, "--help"] },
    comparison: HELP_EXISTS,
  })),
  {
    id: "completion-command",
    description: "Both CLIs generate a shell completion script for a requested shell.",
    tags: ["surface", "completion"],
    invocation: { args: ["completion", "bash"] },
    comparison: {
      exitCode: 0,
      stdout: { kind: "nonempty" },
      stderr: { kind: "ignore" },
    },
  },
  {
    id: "known-difference-version-flag",
    description: "Rust CLI exposes a --version flag; Go CLI exposes a version subcommand.",
    tags: ["known-difference", "surface", "version"],
    invocation: { args: ["--version"] },
    knownDifference: {
      id: "version-flag",
      summary: "Rust CLI accepts 'mcap --version'; Go CLI only accepts 'mcap version'.",
      reason:
        "Rust CLI intentionally exposes version information through the standard --version flag instead of a dedicated subcommand.",
      desiredBehavior:
        "Rust CLI should continue to support --version; the 'version' subcommand remains Go-only by design.",
      goBehavior: {
        exitCode: "nonzero",
        stderr: { kind: "contains", value: "unknown flag: --version" },
      },
      rustBehavior: {
        exitCode: 0,
        stdout: { kind: "nonempty" },
      },
    },
  },
  {
    id: "cat-one-message",
    description: "Basic cat output matches for an indexed MCAP with one schematized message.",
    tags: ["cat", "stdout"],
    invocation: { args: ["cat", ONE_MESSAGE] },
    comparison: {
      exitCode: 0,
      stdout: { kind: "bytes" },
      stderr: { kind: "text" },
    },
  },
  {
    id: "cat-one-schemaless-message",
    description: "Basic cat output matches for an indexed MCAP with one schemaless message.",
    tags: ["cat", "stdout"],
    invocation: { args: ["cat", ONE_SCHEMALESS] },
    comparison: {
      exitCode: 0,
      stdout: { kind: "bytes" },
      stderr: { kind: "text" },
    },
  },
  {
    id: "cat-topic-filter-includes-matching-topic",
    description: "Cat topic filtering includes messages on requested topics.",
    tags: ["cat", "stdout", "topics"],
    invocation: { args: ["cat", ONE_MESSAGE, "--topics", "example"] },
    comparison: {
      exitCode: 0,
      stdout: { kind: "bytes" },
      stderr: { kind: "text" },
    },
  },
  {
    id: "cat-topic-filter-excludes-missing-topic",
    description: "Cat topic filtering emits no messages when no requested topic matches.",
    tags: ["cat", "stdout", "topics"],
    invocation: { args: ["cat", ONE_MESSAGE, "--topics", "missing"] },
    comparison: {
      exitCode: 0,
      stdout: { kind: "text" },
      stderr: { kind: "text" },
    },
  },
  {
    id: "cat-time-filter-includes-range",
    description: "Cat time filtering includes messages in the requested nanosecond range.",
    tags: ["cat", "stdout", "time"],
    invocation: { args: ["cat", ONE_MESSAGE, "--start-nsecs", "2", "--end-nsecs", "3"] },
    comparison: {
      exitCode: 0,
      stdout: { kind: "bytes" },
      stderr: { kind: "text" },
    },
  },
  {
    id: "cat-time-filter-excludes-out-of-range",
    description: "Cat time filtering emits no messages outside the requested range.",
    tags: ["cat", "stdout", "time"],
    invocation: { args: ["cat", ONE_MESSAGE, "--start-nsecs", "3"] },
    comparison: {
      exitCode: 0,
      stdout: { kind: "text" },
      stderr: { kind: "text" },
    },
  },
  {
    id: "cat-stdin-one-message",
    description: "Cat reads stdin when no file argument is supplied.",
    tags: ["cat", "stdout", "stdin"],
    invocation: { args: ["cat"], stdin: { path: ONE_MESSAGE } },
    comparison: {
      exitCode: 0,
      stdout: { kind: "bytes" },
      stderr: { kind: "text" },
    },
  },
  {
    id: "cat-json-unsupported-schema-errors",
    description:
      "Cat --json accepts the flag and errors consistently for unsupported schema encodings.",
    tags: ["cat", "json"],
    invocation: { args: ["cat", ONE_MESSAGE, "--json"] },
    comparison: {
      exitCode: "same",
      stdout: { kind: "text" },
      stderr: { kind: "ignore" },
    },
  },
  {
    id: "cat-json-protobuf-stdin",
    description:
      "Cat --json emits protobuf messages as NDJSON with Go-compatible field casing and zero-value omission.",
    tags: ["cat", "json", "protobuf", "stdin"],
    setup: [
      {
        type: "writeProtobufJsonMcap",
        to: "{caseWorkDir}/protobuf.mcap",
        messages: [
          {
            sequence: 1,
            logTime: 2,
            publishTime: 1,
            snakeCase: "hello",
            zeroValue: 0,
            count: 7,
          },
          {
            sequence: 2,
            logTime: 3,
            publishTime: 2,
            snakeCase: "world",
            zeroValue: 0,
            count: 8,
          },
        ],
      },
    ],
    invocation: { args: ["cat", "--json"], stdin: { path: "{caseWorkDir}/protobuf.mcap" } },
    comparison: {
      exitCode: 0,
      stdout: { kind: "ndjson" },
      stderr: { kind: "text" },
    },
  },
  {
    id: "cat-json-ros1msg-stdin",
    description:
      "Cat --json emits ROS1 messages as NDJSON with Go-compatible nested message, special float, duration, and array output.",
    tags: ["cat", "json", "ros1msg", "stdin"],
    setup: [
      {
        type: "writeRos1JsonMcap",
        to: "{caseWorkDir}/ros1.mcap",
        messages: [
          {
            sequence: 1,
            logTime: 2,
            publishTime: 1,
            headerSeq: 7,
            stampSec: 1,
            stampNsec: 2,
            frameId: "map",
            durationSec: 4,
            durationNsec: 5,
            values: [10, 20],
          },
          {
            sequence: 2,
            logTime: 3,
            publishTime: 2,
            headerSeq: 8,
            stampSec: 2,
            stampNsec: 3,
            frameId: "odom",
            durationSec: 5,
            durationNsec: 6,
            values: [30],
          },
        ],
      },
    ],
    invocation: { args: ["cat", "--json"], stdin: { path: "{caseWorkDir}/ros1.mcap" } },
    comparison: {
      exitCode: 0,
      stdout: { kind: "ndjson" },
      stderr: { kind: "text" },
    },
  },
  {
    id: "info-one-message",
    description: "Info output reports the same stable summary fields for a representative MCAP.",
    tags: ["info", "stdout"],
    invocation: { args: ["info", ONE_MESSAGE] },
    comparison: {
      exitCode: 0,
      // The `info` comparator ignores only the duration line (Go `0s` vs Rust `0ns` for this
      // zero-duration fixture, pinned by the info-timestamp-format known difference below); start/end
      // are compared and match here as decimal seconds since this fixture is below the 2000 cutoff.
      stdout: { kind: "info" },
      stderr: { kind: "text" },
    },
  },
  {
    id: "known-difference-info-timestamp-format",
    description:
      "Below the 2000-01-01 cutoff both CLIs render start/end as decimal seconds only; they differ only on the zero-duration unit (Go `0s` vs Rust `0ns`).",
    tags: ["known-difference", "info"],
    invocation: { args: ["info", ONE_MESSAGE] },
    knownDifference: {
      id: "info-timestamp-format",
      summary:
        "For this near-epoch fixture both CLIs render start/end as decimal seconds, so the only asserted difference is the zero-duration unit (Go `0s`, Rust `0ns`).",
      reason:
        "Rust renders the raw decimal seconds below the 2000-01-01 cutoff (946684800s) and an RFC3339 wall-clock string with the epoch decimal in parens at/after it — the same shape Go uses. Near-epoch/relative timestamps therefore render as a plain decimal offset rather than a misleading 1970 date, while real recordings show the human date. For this fixture's 2ns start, Rust matches Go's decimal-only rendering (neither emits `1970-...Z`); wall-clock parity at/after the cutoff is covered by the info-timestamp-wall-clock-format case below. The remaining difference asserted here is the zero-duration unit: Go `0s`, Rust `0ns`.",
      desiredBehavior:
        "Rust's start/end rendering — decimal seconds below the 2000-01-01 cutoff, `RFC3339 (epoch decimal)` at/after it — matches Go; the zero-duration unit difference (`0s` vs `0ns`) is cosmetic and unresolved.",
      // Go renders near-epoch times as decimal seconds only (no RFC3339 / no `1970-...Z`) and a zero
      // duration as `0s`.
      goBehavior: {
        exitCode: 0,
        stdout: {
          kind: "matches",
          pattern:
            "^(?![\\s\\S]*1970-01-01)(?=[\\s\\S]*duration:\\s+0s)[\\s\\S]*start:\\s+0\\.000000002[\\s\\S]*$",
        },
      },
      // Below the cutoff Rust also renders decimal-only (no `1970-...Z`), matching Go; only the zero
      // duration differs (`0ns`).
      rustBehavior: {
        exitCode: 0,
        stdout: {
          kind: "matches",
          pattern:
            "^(?![\\s\\S]*1970-01-01)(?=[\\s\\S]*duration:\\s+0ns)[\\s\\S]*start:\\s+0\\.000000002[\\s\\S]*$",
        },
      },
    },
  },
  {
    id: "info-timestamp-wall-clock-format",
    description:
      "For a wall-clock (>= 2000) timestamp, both CLIs render start/end as `RFC3339 (epoch decimal)`.",
    tags: ["info", "stdout"],
    // Pin TZ=UTC: Go renders info timestamps in the host's local time zone while Rust always renders
    // UTC (`Z`), so without this the start/end lines would only line up on a UTC host. With TZ=UTC
    // both show the same instant, and the `info` comparator (which no longer drops start/end) checks
    // that both emit the identical `2017-...Z (1490149580.103843113)` form.
    invocation: { args: ["info", WALL_CLOCK_MCAP], env: { TZ: "UTC" } },
    comparison: {
      exitCode: 0,
      stdout: { kind: "info" },
      stderr: { kind: "text" },
    },
  },
  {
    id: "list-channels",
    description: "Channel listing contains the same table data despite formatter differences.",
    tags: ["list", "table"],
    invocation: { args: ["list", "channels", ONE_MESSAGE] },
    comparison: {
      exitCode: 0,
      stdout: { kind: "table" },
      stderr: { kind: "text" },
    },
  },
  {
    id: "list-chunks",
    description: "Chunk listing contains the same table data despite formatter differences.",
    tags: ["list", "table", "chunks"],
    invocation: { args: ["list", "chunks", ONE_MESSAGE] },
    comparison: {
      exitCode: 0,
      stdout: { kind: "table" },
      stderr: { kind: "text" },
    },
  },
  {
    id: "list-schemas",
    description: "Schema listing contains the same table data despite formatter differences.",
    tags: ["list", "table", "schemas"],
    invocation: { args: ["list", "schemas", ONE_MESSAGE] },
    comparison: {
      exitCode: 0,
      stdout: { kind: "table" },
      stderr: { kind: "text" },
    },
  },
  {
    id: "list-metadata",
    description: "Metadata listing contains the same table data despite formatter differences.",
    tags: ["list", "table", "metadata"],
    invocation: { args: ["list", "metadata", ONE_METADATA] },
    comparison: {
      exitCode: 0,
      stdout: { kind: "table" },
      stderr: { kind: "text" },
    },
  },
  {
    id: "list-attachments",
    description: "Attachment listing contains the same table data despite formatter differences.",
    tags: ["list", "table", "attachments"],
    invocation: { args: ["list", "attachments", ONE_ATTACHMENT] },
    comparison: {
      exitCode: 0,
      stdout: { kind: "table" },
      stderr: { kind: "text" },
    },
  },
  {
    id: "get-metadata-json",
    description: "Metadata extraction returns the same JSON object.",
    tags: ["get", "metadata", "json"],
    invocation: { args: ["get", "metadata", ONE_METADATA, "--name", "myMetadata"] },
    comparison: {
      exitCode: 0,
      stdout: { kind: "json" },
      stderr: { kind: "text" },
    },
  },
  {
    id: "get-attachment-by-name",
    description: "Attachment extraction by name writes identical payload bytes.",
    tags: ["get", "attachments", "bytes"],
    invocation: {
      args: ["get", "attachment", ONE_ATTACHMENT, "--name", "myFile", "-o", "attachment.bin"],
    },
    comparison: {
      exitCode: 0,
      stdout: { kind: "text" },
      stderr: { kind: "text" },
      files: [{ path: "attachment.bin", comparator: { kind: "bytes" } }],
    },
  },
  {
    id: "get-attachment-by-offset",
    description: "Attachment extraction by record offset writes identical payload bytes.",
    tags: ["get", "attachments", "bytes", "offset"],
    invocation: {
      args: [
        "get",
        "attachment",
        ONE_ATTACHMENT,
        "--name",
        "myFile",
        "--offset",
        ONE_ATTACHMENT_RECORD_OFFSET,
        "-o",
        "attachment.bin",
      ],
    },
    comparison: {
      exitCode: 0,
      stdout: { kind: "text" },
      stderr: { kind: "text" },
      files: [{ path: "attachment.bin", comparator: { kind: "bytes" } }],
    },
  },
  {
    id: "doctor-valid-file-exits-successfully",
    description:
      "Doctor accepts a representative valid MCAP; warning stream differences are covered separately.",
    tags: ["doctor"],
    invocation: { args: ["doctor", ONE_MESSAGE] },
    comparison: EXIT_CODE_ONLY,
  },
  {
    id: "doctor-strict-message-order-detects-out-of-order-log-time",
    description: "Doctor strict message ordering rejects messages whose log times move backward.",
    tags: ["doctor", "strict-message-order"],
    setup: [
      {
        type: "writeProtobufJsonMcap",
        to: "{caseWorkDir}/out-of-order.mcap",
        chunkedMessages: true,
        messages: [
          {
            sequence: 1,
            logTime: 3,
            publishTime: 1,
            snakeCase: "later",
            count: 1,
          },
          {
            sequence: 2,
            logTime: 2,
            publishTime: 2,
            snakeCase: "earlier",
            count: 2,
          },
        ],
      },
    ],
    invocation: { args: ["doctor", "--strict-message-order", "out-of-order.mcap"] },
    comparison: {
      exitCode: 1,
      stdout: { kind: "ignore" },
      stderr: { kind: "ignore" },
    },
  },
  ...[
    {
      id: "convert-noetic-ros1-bag-none",
      fixture: NOETIC_MULTITOPIC_NONE,
      description: "Converting a Noetic ROS1 bag with uncompressed chunks preserves messages.",
      tags: ["convert", "ros1", "mcap-output"],
    },
    {
      id: "convert-noetic-ros1-bag-bz2",
      fixture: NOETIC_MULTITOPIC_BZ2,
      description: "Converting a Noetic ROS1 bag with bz2 chunks preserves messages.",
      tags: ["convert", "ros1", "mcap-output", "bz2"],
    },
    {
      id: "convert-noetic-ros1-bag-lz4",
      fixture: NOETIC_MULTITOPIC_LZ4,
      description: "Converting a Noetic ROS1 bag with lz4 chunks preserves messages.",
      tags: ["convert", "ros1", "mcap-output", "lz4"],
    },
  ].map<CliTestCase>((testCase) => ({
    id: testCase.id,
    description: testCase.description,
    tags: testCase.tags,
    invocation: {
      args: ["convert", testCase.fixture, "converted.mcap", "--compression", "none"],
    },
    goInvocation: {
      args: [
        "convert",
        testCase.fixture,
        "converted.mcap",
        "--compression",
        "none",
        "--include-crc=false",
      ],
    },
    rustInvocation: {
      args: ["convert", testCase.fixture, "converted.mcap", "--compression", "none", "--no-crc"],
    },
    comparison: {
      exitCode: 0,
      stdout: { kind: "ignore" },
      stderr: { kind: "ignore" },
      files: [
        {
          path: "converted.mcap",
          comparator: { kind: "mcap", mode: "content", allowSemanticFallback: true },
        },
      ],
    },
  })),
  {
    id: "filter-topic-output-messages",
    description: "Filtering by topic preserves the same message stream.",
    tags: ["filter", "mcap-output"],
    invocation: {
      args: [
        "filter",
        TEN_MESSAGES,
        "-o",
        "filtered.mcap",
        "-y",
        "example",
        "--output-compression",
        "none",
      ],
    },
    comparison: {
      exitCode: 0,
      stdout: { kind: "text" },
      stderr: { kind: "text", collapseWhitespace: true },
      files: [
        {
          path: "filtered.mcap",
          comparator: { kind: "mcap", mode: "content", allowSemanticFallback: true },
        },
      ],
    },
  },
  {
    id: "filter-exclude-topic-output-messages",
    description:
      "Rust filter excludes -n/--exclude-topic-regex topics; Go filter leaks all messages when the exclude matches every topic.",
    tags: ["known-difference", "filter", "mcap-output", "topics"],
    invocation: {
      args: [
        "filter",
        TEN_MESSAGES,
        "-o",
        "filtered.mcap",
        "-n",
        "example",
        "--output-compression",
        "none",
      ],
    },
    knownDifference: {
      id: "filter-exclude-topic-regex",
      summary:
        "Rust filter correctly excludes matching topics with -n/--exclude-topic-regex; Go filter leaks every message when the exclude regex matches all topics.",
      reason:
        "Go honors -n in general, but when the exclude regex eliminates every channel's topic the resulting empty topic set is treated by the indexed reader as `no filter` (an empty topic list means all topics), so every message passes through. This fixture has a single topic `example`, so excluding it leaves Go emitting all 10 messages — a silently unfiltered file — while Rust drops the matching channels to 0. (In a multi-topic file where -n removes only some topics, the topic set is non-empty and Go filters correctly.)",
      desiredBehavior:
        "Rust filter's exclusion behavior is the intended, correct behavior; Go treating an exclude-everything result as `no filter` is a known Go bug that will not be fixed before the Go CLI is retired.",
      goBehavior: {
        exitCode: 0,
        files: [
          {
            path: "filtered.mcap",
            exists: true,
            mcapSummary: { messageCount: 10, channelCount: 1, schemaCount: 1 },
          },
        ],
      },
      rustBehavior: {
        exitCode: 0,
        files: [
          {
            path: "filtered.mcap",
            exists: true,
            mcapSummary: { messageCount: 0, channelCount: 0, schemaCount: 0 },
          },
        ],
      },
    },
  },
  {
    id: "filter-rfc3339-time-range-output-messages",
    description: "Filtering with RFC3339 start/end bounds preserves the same message stream.",
    tags: ["filter", "mcap-output", "time"],
    invocation: {
      args: [
        "filter",
        ONE_MESSAGE,
        "-o",
        "filtered.mcap",
        "-S",
        "1970-01-01T00:00:00.000000002Z",
        "-E",
        "1970-01-01T00:00:00.000000003Z",
        "--output-compression",
        "none",
      ],
    },
    comparison: {
      exitCode: 0,
      stdout: { kind: "text" },
      stderr: { kind: "text", collapseWhitespace: true },
      files: [
        {
          path: "filtered.mcap",
          comparator: { kind: "mcap", mode: "content", allowSemanticFallback: true },
        },
      ],
    },
  },
  {
    id: "filter-includes-metadata-and-attachments",
    description: "Filtering with metadata and attachment flags preserves non-message records.",
    tags: ["filter", "mcap-output", "metadata", "attachments"],
    setup: [
      {
        type: "writeProtobufJsonMcap",
        to: "{caseWorkDir}/content.mcap",
        messages: [
          {
            sequence: 1,
            logTime: 2,
            publishTime: 1,
            snakeCase: "hello",
            count: 7,
          },
        ],
        metadata: [{ name: "cli-conformance", metadata: { key: "value" } }],
        attachments: [
          {
            name: "payload.bin",
            mediaType: "application/octet-stream",
            logTime: 4,
            createTime: 3,
            data: [1, 1, 2, 3, 5, 8],
          },
        ],
      },
    ],
    invocation: {
      args: [
        "filter",
        "content.mcap",
        "-o",
        "filtered.mcap",
        "--include-metadata",
        "--include-attachments",
        "--output-compression",
        "none",
      ],
    },
    comparison: {
      exitCode: 0,
      stdout: { kind: "text" },
      stderr: { kind: "text", collapseWhitespace: true },
      files: [
        {
          path: "filtered.mcap",
          comparator: { kind: "mcap", mode: "content", allowSemanticFallback: true },
        },
      ],
    },
  },
  {
    id: "compress-none-output-messages",
    description: "Rewriting an MCAP with no output compression preserves the same message stream.",
    tags: ["compress", "mcap-output"],
    invocation: {
      args: ["compress", TEN_MESSAGES, "-o", "compressed.mcap", "--compression", "none"],
    },
    comparison: {
      exitCode: 0,
      stdout: { kind: "text" },
      stderr: { kind: "text", collapseWhitespace: true },
      files: [
        {
          path: "compressed.mcap",
          comparator: { kind: "mcap", mode: "content", allowSemanticFallback: true },
        },
      ],
    },
  },
  {
    id: "compress-lz4-output-messages",
    description: "Rewriting an MCAP with lz4 compression preserves the same message stream.",
    tags: ["compress", "mcap-output", "lz4"],
    invocation: {
      args: ["compress", TEN_MESSAGES, "-o", "compressed-lz4.mcap", "--compression", "lz4"],
    },
    comparison: {
      exitCode: 0,
      stdout: { kind: "text" },
      stderr: { kind: "text", collapseWhitespace: true },
      files: [
        {
          path: "compressed-lz4.mcap",
          comparator: { kind: "mcap", mode: "content", allowSemanticFallback: true },
        },
      ],
    },
  },
  {
    id: "compress-zstd-output-messages",
    description: "Rewriting an MCAP with zstd compression preserves the same message stream.",
    tags: ["compress", "mcap-output", "zstd"],
    invocation: {
      args: ["compress", TEN_MESSAGES, "-o", "compressed-zstd.mcap", "--compression", "zstd"],
    },
    comparison: {
      exitCode: 0,
      stdout: { kind: "text" },
      stderr: { kind: "text", collapseWhitespace: true },
      files: [
        {
          path: "compressed-zstd.mcap",
          comparator: { kind: "mcap", mode: "content", allowSemanticFallback: true },
        },
      ],
    },
  },
  {
    id: "decompress-output-messages",
    description: "Decompressing an MCAP preserves the same message stream.",
    tags: ["decompress", "mcap-output"],
    invocation: {
      args: ["decompress", TEN_MESSAGES, "-o", "decompressed.mcap"],
    },
    comparison: {
      exitCode: 0,
      stdout: { kind: "text" },
      stderr: { kind: "text", collapseWhitespace: true },
      files: [
        {
          path: "decompressed.mcap",
          comparator: { kind: "mcap", mode: "content", allowSemanticFallback: true },
        },
      ],
    },
  },
  {
    id: "sort-output-messages",
    description: "Sorting an indexed MCAP preserves the same message stream.",
    tags: ["sort", "mcap-output"],
    invocation: {
      args: ["sort", TEN_MESSAGES, "-o", "sorted.mcap"],
    },
    comparison: {
      exitCode: 0,
      stdout: { kind: "text" },
      stderr: { kind: "text", collapseWhitespace: true },
      files: [
        {
          path: "sorted.mcap",
          comparator: { kind: "mcap", mode: "content", allowSemanticFallback: true },
        },
      ],
    },
  },
  {
    id: "merge-output-messages",
    description: "Merging multiple MCAP files preserves the same combined message stream.",
    tags: ["merge", "mcap-output"],
    invocation: {
      args: ["merge", ONE_MESSAGE, ONE_SCHEMALESS, "-o", "merged.mcap", "--compression", "none"],
    },
    comparison: {
      exitCode: 0,
      stdout: { kind: "text" },
      stderr: { kind: "text", collapseWhitespace: true },
      files: [
        {
          path: "merged.mcap",
          comparator: { kind: "mcap", mode: "content", allowSemanticFallback: true },
        },
      ],
    },
  },
  {
    id: "merge-coalesce-channels-none-output-messages",
    description:
      "Merging with channel coalescing disabled preserves the same combined message stream.",
    tags: ["merge", "mcap-output", "coalesce-channels"],
    invocation: {
      args: [
        "merge",
        ONE_MESSAGE,
        ONE_MESSAGE,
        "-o",
        "merged-no-coalesce.mcap",
        "--compression",
        "none",
        "--coalesce-channels",
        "none",
      ],
    },
    comparison: {
      exitCode: 0,
      stdout: { kind: "text" },
      stderr: { kind: "text", collapseWhitespace: true },
      files: [
        {
          path: "merged-no-coalesce.mcap",
          comparator: { kind: "mcap", mode: "content", allowSemanticFallback: true },
        },
      ],
    },
  },
  {
    id: "recover-valid-output-messages",
    description: "Recovering a valid MCAP preserves the same message stream.",
    tags: ["recover", "mcap-output"],
    invocation: {
      args: ["recover", TEN_MESSAGES, "-o", "recovered.mcap", "--compression", "none"],
    },
    comparison: {
      exitCode: 0,
      stdout: { kind: "text" },
      stderr: { kind: "text", collapseWhitespace: true },
      files: [
        {
          path: "recovered.mcap",
          comparator: { kind: "mcap", mode: "content", allowSemanticFallback: true },
        },
      ],
    },
  },
  {
    id: "add-metadata-mutates-file-content",
    description: "Adding deterministic metadata produces equivalent message and metadata content.",
    tags: ["add", "metadata", "mcap-output"],
    setup: [{ type: "copy", from: TEN_MESSAGES, to: "{caseWorkDir}/input.mcap" }],
    invocation: {
      args: ["add", "metadata", "input.mcap", "--name", "cli-conformance", "-k", "key=value"],
    },
    comparison: {
      exitCode: 0,
      stdout: { kind: "text" },
      stderr: { kind: "text", collapseWhitespace: true },
      files: [
        {
          path: "input.mcap",
          comparator: { kind: "mcap", mode: "content", allowSemanticFallback: true },
        },
      ],
    },
  },
  {
    id: "add-attachment-mutates-file-content",
    description:
      "Adding a deterministic attachment produces equivalent message and attachment content.",
    tags: ["add", "attachments", "mcap-output"],
    setup: [
      { type: "copy", from: TEN_MESSAGES, to: "{caseWorkDir}/input.mcap" },
      { type: "writeBytes", to: "{caseWorkDir}/payload.bin", bytes: [1, 1, 2, 3, 5, 8] },
    ],
    invocation: {
      args: [
        "add",
        "attachment",
        "input.mcap",
        "-f",
        "payload.bin",
        "-n",
        "payload.bin",
        "--log-time",
        "42",
        "--creation-time",
        "24",
      ],
    },
    comparison: {
      exitCode: 0,
      stdout: { kind: "text" },
      stderr: { kind: "text", collapseWhitespace: true },
      files: [
        {
          path: "input.mcap",
          comparator: { kind: "mcap", mode: "content", allowSemanticFallback: true },
        },
      ],
    },
  },
  {
    id: "known-difference-recover-lossy-exit-code",
    description:
      "On a truncated MCAP, Rust recover exits 3 (recovered but lossy); Go recover exits 0.",
    tags: ["known-difference", "recover"],
    setup: [
      { type: "copy", from: TEN_MESSAGES, to: "{caseWorkDir}/truncated.mcap" },
      // Cut mid-chunk so only some of the messages are recovered and the data section never
      // reaches a clean DataEnd (TEN_MESSAGES is ~1083 bytes; the chunk spans past byte 300).
      { type: "truncate", path: "{caseWorkDir}/truncated.mcap", size: 300 },
    ],
    invocation: { args: ["recover", "truncated.mcap", "-o", "recovered.mcap"] },
    knownDifference: {
      id: "recover-lossy-exit-code",
      summary:
        "Rust recover exits non-zero (3) when recovery is lossy; Go recover exits 0 once recovery starts.",
      reason:
        "Rust recover signals data loss through the exit code (0 = clean, 1 = nothing recovered, 3 = recovered but lossy) so a partial salvage is not silently reported as success. Go recover returns success on any started recovery, including truncated input.",
      desiredBehavior:
        "Rust recover should exit 3 when one or more messages/records are discarded or the input is truncated mid-record; a clean recovery exits 0 and nothing-recovered exits 1.",
      goBehavior: {
        exitCode: 0,
        files: [{ path: "recovered.mcap", exists: true }],
      },
      rustBehavior: {
        exitCode: 3,
        files: [{ path: "recovered.mcap", exists: true }],
      },
    },
  },
  {
    id: "known-difference-recover-always-decode-chunk-flag",
    description:
      "Go recover accepts --always-decode-chunk; Rust recover removed the flag because it always decodes and re-encodes chunks.",
    tags: ["known-difference", "recover", "surface"],
    invocation: {
      args: ["recover", TEN_MESSAGES, "-o", "recovered.mcap", "--always-decode-chunk"],
    },
    knownDifference: {
      id: "recover-always-decode-chunk-flag",
      summary: "Go recover accepts an --always-decode-chunk flag; Rust recover does not expose it.",
      reason:
        "Rust recover always decodes and validates every chunk and re-encodes records through the writer, so a decode toggle is unnecessary; the --compression flag alone selects the output codec. Rust recover also guarantees a valid, readable output and defaults to --compression preserve, whereas Go copies chunk bytes through verbatim and defaults to zstd.",
      desiredBehavior:
        "Rust recover should keep decoding chunks unconditionally; the --always-decode-chunk flag remains Go-only.",
      goBehavior: {
        exitCode: 0,
        files: [{ path: "recovered.mcap", exists: true }],
      },
      rustBehavior: {
        exitCode: "nonzero",
        stderr: { kind: "contains", value: "--always-decode-chunk" },
      },
    },
  },
  {
    id: "known-difference-version-subcommand",
    description: "Go CLI exposes a 'version' subcommand; Rust CLI only exposes the --version flag.",
    tags: ["known-difference", "surface", "version"],
    invocation: { args: ["version"] },
    knownDifference: {
      id: "version-subcommand",
      summary:
        "Go CLI accepts 'mcap version' as a subcommand; Rust CLI only supports 'mcap --version'.",
      reason:
        "Rust CLI intentionally exposes version information through the standard --version flag instead of a dedicated subcommand.",
      desiredBehavior:
        "Rust CLI should continue to support --version; the 'version' subcommand remains Go-only by design.",
      goBehavior: {
        exitCode: 0,
        stdout: { kind: "anything" },
      },
      rustBehavior: {
        exitCode: "nonzero",
        stderr: { kind: "contains", value: "unrecognized" },
      },
    },
  },
  {
    id: "known-difference-convert-ros2-ament-help",
    description:
      "Go CLI exposes ament-based ROS 2 db3 conversion; Rust CLI intentionally supports embedded-schema db3 conversion instead.",
    tags: ["known-difference", "convert", "surface"],
    invocation: { args: ["convert", "--help"] },
    knownDifference: {
      id: "convert-ros2-ament-help",
      summary:
        "Go convert exposes --ament-prefix-path for ROS 2 db3 conversion; Rust convert does not.",
      reason:
        "Rust convert avoids brittle ament workspace lookup and only converts ROS 2 db3 bags that contain embedded message definitions.",
      desiredBehavior:
        "Rust convert should continue to document the embedded-schema-only behavior for ROS 2 db3 conversion.",
      goBehavior: {
        exitCode: 0,
        stdout: { kind: "contains", value: "--ament-prefix-path" },
      },
      rustBehavior: {
        exitCode: 0,
        stdout: { kind: "matches", pattern: "^(?![\\s\\S]*ament-prefix-path)[\\s\\S]*$" },
      },
    },
  },
  {
    id: "known-difference-convert-ros2-db3-embedded-schemas",
    description:
      "Rust converts self-contained ROS 2 db3 bags with embedded schemas; Go requires ament schemas.",
    tags: ["known-difference", "convert", "ros2"],
    invocation: {
      args: ["convert", ROS2_EMBEDDED_SCHEMA_DB3, "converted.mcap", "--compression", "none"],
      // Make Go's ament-only schema lookup deterministic even when the developer shell has
      // sourced a ROS 2 workspace. Rust does not consult this environment variable.
      env: { AMENT_PREFIX_PATH: "" },
    },
    knownDifference: {
      id: "convert-ros2-db3-embedded-schemas",
      summary:
        "Rust convert reads embedded ROS 2 db3 schemas, while Go convert ignores them and requires ament lookup.",
      reason:
        "The Rust replacement intentionally supports self-contained db3 conversion and omits brittle ament lookup; the legacy Go converter predates embedded db3 schemas.",
      desiredBehavior:
        "Rust convert should continue to convert self-contained ROS 2 db3 bags without requiring a ROS workspace.",
      goBehavior: {
        exitCode: "nonzero",
        stderr: { kind: "contains", value: "schema not found" },
      },
      rustBehavior: {
        exitCode: 0,
        files: [
          {
            path: "converted.mcap",
            exists: true,
            mcapSummary: { profile: "ros2", messageCount: 20, channelCount: 3, schemaCount: 3 },
          },
        ],
      },
    },
  },
  {
    id: "known-difference-convert-extension-dispatch",
    description:
      "Rust convert dispatches by input extension; Go convert dispatches by magic bytes.",
    tags: ["known-difference", "convert", "surface"],
    setup: [{ type: "copy", from: NOETIC_MULTITOPIC_NONE, to: "{caseWorkDir}/input.notbag" }],
    invocation: {
      args: ["convert", "input.notbag", "converted.mcap", "--compression", "none"],
    },
    knownDifference: {
      id: "convert-extension-dispatch",
      summary:
        "Go convert accepts supported inputs with non-standard extensions by magic bytes; Rust convert requires known extensions.",
      reason:
        "Rust convert uses a central extension-to-converter mapping so converters own format validation after dispatch.",
      desiredBehavior:
        "Rust convert should keep extension-based dispatch unless a future CLI design adds explicit input-format selection.",
      goBehavior: {
        exitCode: 0,
        files: [
          {
            path: "converted.mcap",
            exists: true,
            mcapSummary: { profile: "ros1", messageCount: 3, channelCount: 2, schemaCount: 2 },
          },
        ],
      },
      rustBehavior: {
        exitCode: "nonzero",
        stderr: { kind: "contains", value: "unsupported input file extension" },
      },
    },
  },
  {
    id: "known-difference-pprof-profile-global",
    description:
      "Go CLI writes pprof profiles; Rust CLI intentionally does not expose --pprof-profile.",
    tags: ["known-difference", "global-options"],
    invocation: { args: ["--pprof-profile", "info", ONE_MESSAGE] },
    knownDifference: {
      id: "global-pprof-profile",
      summary:
        "Go CLI implements --pprof-profile; the Rust CLI intentionally omits the flag and rejects it as an unknown argument.",
      reason:
        "The Go flag is built on Go's runtime/pprof profiler and emits Go-pprof-format artifacts that have no equivalent in Rust. Profiling Rust builds is done with external tooling (for example perf, cargo flamegraph, or samply) rather than a baked-in flag, so the Rust CLI deliberately does not carry it.",
      desiredBehavior:
        "Rust CLI should not expose --pprof-profile; the flag remains Go-only by design.",
      goBehavior: {
        exitCode: 0,
        files: [
          { path: "mcap-cpu.prof", exists: true },
          { path: "mcap-mem.prof", exists: true },
          { path: "mcap-block.pprof", exists: true },
        ],
      },
      rustBehavior: {
        exitCode: 2,
        stderr: { kind: "contains", value: "unexpected argument '--pprof-profile'" },
      },
    },
  },
  {
    id: "known-difference-du-record-accounting",
    description:
      "Rust du counts the full on-disk size of each record; Go du undercounts by omitting record framing.",
    tags: ["known-difference", "du"],
    invocation: { args: ["du", ONE_MESSAGE] },
    knownDifference: {
      id: "du-record-accounting",
      summary:
        "Rust du reports the correct on-disk record byte counts; Go du undercounts every record by its 9-byte framing (opcode + length).",
      reason:
        "Each MCAP record occupies a 1-byte opcode and an 8-byte length prefix on disk in addition to its content. Rust du counts that framing, so the per-record totals account for every byte in the file apart from the 16 bytes of leading/trailing magic (here for ONE_MESSAGE they sum to 617 of the 633-byte file). Go du omits the framing, undercounting every record by 9 bytes (chunk = 155 instead of 164) and also skips attachment records entirely.",
      desiredBehavior:
        "Rust du's full-record accounting is the intended, more correct behavior; the Go undercount is a known Go bug that will not be fixed before the Go CLI is retired.",
      goBehavior: {
        exitCode: 0,
        stdout: { kind: "contains", value: "chunk         \t155" },
      },
      rustBehavior: {
        exitCode: 0,
        stdout: { kind: "contains", value: "chunk         \t164" },
      },
    },
  },
  {
    id: "known-difference-doctor-warning-stream",
    description:
      "Rust doctor writes diagnostics to stderr; Go doctor writes them to stdout, polluting the results stream.",
    tags: ["known-difference", "doctor"],
    invocation: { args: ["doctor", ONE_MESSAGE] },
    knownDifference: {
      id: "doctor-warning-stream",
      summary:
        "Rust doctor prints the header-library warning to stderr (the correct stream for diagnostics); Go doctor prints it to stdout.",
      reason:
        "Diagnostics belong on stderr so stdout stays reserved for machine-consumable results; Rust follows this convention. Go writes doctor warnings/errors to stdout, which pollutes the results stream and is inconsistent with how the other Rust commands split output. This also matches the doctor-reports-all-structural-errors case, which documents Rust's error reporting on stderr.",
      desiredBehavior:
        "Rust doctor's use of stderr for diagnostics is the intended behavior; the Go stdout output is a known Go bug that will not be fixed before the Go CLI is retired.",
      goBehavior: {
        exitCode: 0,
        stdout: { kind: "contains", value: "Header.library" },
      },
      rustBehavior: {
        exitCode: 0,
        stderr: { kind: "contains", value: "Header.library" },
      },
    },
  },
  {
    id: "known-difference-config-global",
    description: "Go CLI accepts a config file; Rust CLI intentionally does not expose --config.",
    tags: ["known-difference", "global-options"],
    setup: [{ type: "writeText", to: "{caseWorkDir}/config.yaml", contents: "{}\n" }],
    invocation: { args: ["--config", "{caseWorkDir}/config.yaml", "info", ONE_MESSAGE] },
    knownDifference: {
      id: "global-config",
      summary:
        "Go CLI accepts --config; the Rust CLI intentionally omits the flag and rejects it as an unknown argument.",
      reason:
        "Go's --config loads a YAML file through viper and prints a confirmation line, but no Go command ever reads a value from it (there are no viper.Get* call sites), so the flag is effectively a no-op. Rather than reproduce a no-op flag, the Rust CLI deliberately omits --config until a real configuration system is designed for both CLIs.",
      desiredBehavior:
        "Rust CLI should not expose --config unless a future, intentionally designed configuration system is added to both CLIs.",
      goBehavior: {
        exitCode: 0,
        stderr: { kind: "contains", value: "Using config file:" },
      },
      rustBehavior: {
        exitCode: 2,
        stderr: { kind: "contains", value: "unexpected argument '--config'" },
      },
    },
  },
  {
    id: "known-difference-cat-unindexed-file-scan",
    description:
      "Rust cat scans an on-disk file without an index; Go cat refuses to read a file that has no index.",
    tags: ["known-difference", "cat"],
    invocation: { args: ["cat", ONE_MESSAGE_UNINDEXED] },
    knownDifference: {
      id: "cat-unindexed-file-scan",
      summary:
        "Rust cat falls back to a linear file-order scan for on-disk MCAPs without an index; Go cat errors instead of reading them.",
      reason:
        "The Rust CLI reads messages in file order when no message index is available, so an unindexed file on disk behaves like piped stdin. The Go CLI only performs file-order reads from stdin and refuses an unindexed file argument.",
      desiredBehavior:
        "Rust cat should continue to read unindexed on-disk files via a linear scan rather than requiring a message index.",
      goBehavior: {
        exitCode: "nonzero",
        stderr: {
          kind: "contains",
          value: "no index available, only file-order reads are supported",
        },
      },
      rustBehavior: {
        exitCode: 0,
        stdout: { kind: "contains", value: "example" },
      },
    },
  },
  {
    id: "known-difference-compress-stdin-pipe",
    description:
      "Rust compress reads a non-seekable stdin pipe; Go compress requires a seekable input and fails on a pipe.",
    tags: ["known-difference", "compress", "stdin"],
    invocation: { args: ["compress", "-o", "out.mcap"], stdin: { path: TEN_MESSAGES } },
    knownDifference: {
      id: "compress-stdin-pipe",
      summary:
        "Rust compress reads a piped (non-seekable) stdin; Go compress fails because it tries to seek stdin.",
      reason:
        "The Go compress path is implemented on top of filter and calls Seek on the input to discover the file size, which fails on a non-seekable pipe. The Rust CLI streams the input and does not require seeking, so `producer | mcap compress -o out.mcap` works.",
      desiredBehavior:
        "Rust compress should continue to accept piped stdin without requiring a seekable input.",
      goBehavior: {
        exitCode: "nonzero",
        stderr: { kind: "contains", value: "illegal seek" },
      },
      rustBehavior: {
        exitCode: 0,
        files: [{ path: "out.mcap", exists: true }],
      },
    },
  },
  {
    id: "known-difference-decompress-stdin-pipe",
    description:
      "Rust decompress reads a non-seekable stdin pipe; Go decompress requires a seekable input and fails on a pipe.",
    tags: ["known-difference", "decompress", "stdin"],
    invocation: { args: ["decompress", "-o", "out.mcap"], stdin: { path: TEN_MESSAGES } },
    knownDifference: {
      id: "decompress-stdin-pipe",
      summary:
        "Rust decompress reads a piped (non-seekable) stdin; Go decompress fails because it tries to seek stdin.",
      reason:
        "The Go decompress path is implemented on top of filter and calls Seek on the input to discover the file size, which fails on a non-seekable pipe. The Rust CLI streams the input and does not require seeking.",
      desiredBehavior:
        "Rust decompress should continue to accept piped stdin without requiring a seekable input.",
      goBehavior: {
        exitCode: "nonzero",
        stderr: { kind: "contains", value: "illegal seek" },
      },
      rustBehavior: {
        exitCode: 0,
        files: [{ path: "out.mcap", exists: true }],
      },
    },
  },
  {
    id: "known-difference-filter-stdin-pipe",
    description:
      "Rust filter reads a non-seekable stdin pipe; Go filter requires a seekable input and fails on a pipe.",
    tags: ["known-difference", "filter", "stdin"],
    invocation: { args: ["filter", "-o", "out.mcap"], stdin: { path: TEN_MESSAGES } },
    knownDifference: {
      id: "filter-stdin-pipe",
      summary:
        "Rust filter reads a piped (non-seekable) stdin; Go filter fails because it tries to seek stdin.",
      reason:
        "Go filter calls Seek on the input to discover the file size, which fails on a non-seekable pipe, so `producer | mcap filter -o out.mcap` errors. The Rust CLI streams the input and does not require seeking.",
      desiredBehavior:
        "Rust filter should continue to accept piped stdin without requiring a seekable input.",
      goBehavior: {
        exitCode: "nonzero",
        stderr: { kind: "contains", value: "illegal seek" },
      },
      rustBehavior: {
        exitCode: 0,
        files: [{ path: "out.mcap", exists: true }],
      },
    },
  },
  {
    id: "known-difference-add-metadata-duplicate-keys",
    description:
      "Rust add metadata rejects duplicate keys; Go add metadata silently keeps the last value.",
    tags: ["known-difference", "add", "metadata"],
    setup: [{ type: "copy", from: TEN_MESSAGES, to: "{caseWorkDir}/input.mcap" }],
    invocation: {
      args: ["add", "metadata", "input.mcap", "--name", "dup", "-k", "a=1", "-k", "a=2"],
    },
    knownDifference: {
      id: "add-metadata-duplicate-keys",
      summary:
        "Rust add metadata fails on duplicate keys; Go add metadata accepts them and keeps the last value.",
      reason:
        "MCAP metadata is a string map, so a duplicate key is ambiguous. The Rust CLI rejects the input to avoid silently dropping a value, while the Go CLI overwrites earlier values with the last one and exits successfully.",
      desiredBehavior:
        "Rust add metadata should keep rejecting duplicate keys rather than silently discarding a value.",
      goBehavior: {
        exitCode: 0,
        files: [
          {
            path: "input.mcap",
            exists: true,
            mcapSummary: { metadata: [{ name: "dup", values: { a: "2" } }] },
          },
        ],
      },
      rustBehavior: {
        exitCode: "nonzero",
        stderr: { kind: "contains", value: "duplicate metadata key" },
      },
    },
  },
  {
    id: "known-difference-completion-invalid-shell",
    description:
      "Rust completion rejects an unknown shell name; Go completion prints help and exits successfully.",
    tags: ["known-difference", "completion", "surface"],
    invocation: { args: ["completion", "notashell"] },
    knownDifference: {
      id: "completion-invalid-shell",
      summary:
        "Rust completion errors on an unknown shell argument; Go completion treats it as a subcommand and prints help with a zero exit code.",
      reason:
        "Rust models the shell as a typed positional value and rejects values outside the supported set. Go models completion as a parent command with per-shell subcommands, so an unknown shell falls through to the command's help text and exits 0.",
      desiredBehavior:
        "Rust completion should keep failing fast on an unsupported shell name instead of silently printing help.",
      goBehavior: {
        exitCode: 0,
        stdout: { kind: "nonempty" },
      },
      rustBehavior: {
        exitCode: 2,
        stderr: { kind: "contains", value: "invalid value 'notashell'" },
      },
    },
  },
  {
    id: "known-difference-missing-required-flag-exit-code",
    description:
      "Rust uses the conventional usage-error exit code 2 for a missing required flag; Go exits 1.",
    tags: ["known-difference", "surface", "sort"],
    invocation: { args: ["sort", ONE_MESSAGE] },
    knownDifference: {
      id: "missing-required-flag-exit-code",
      summary:
        "Rust exits 2 (the conventional usage-error code) when a required flag is missing; Go exits 1.",
      reason:
        "Clap reports argument/usage errors with exit code 2, matching common Unix convention, while Cobra reports them with exit code 1. Both CLIs still print a usage error and require the flag.",
      desiredBehavior:
        "Rust should keep using exit code 2 for argument/usage errors across all commands.",
      goBehavior: {
        exitCode: 1,
        stderr: { kind: "contains", value: "required flag" },
      },
      rustBehavior: {
        exitCode: 2,
        stderr: { kind: "contains", value: "required arguments" },
      },
    },
  },
  {
    id: "known-difference-recover-library-header",
    description:
      "Recover sets the output Header.library differently: Rust preserves the source library, Go writes its own writer identity.",
    tags: ["known-difference", "recover"],
    setup: [{ type: "copy", from: TEN_MESSAGES, to: "{caseWorkDir}/input.mcap" }],
    invocation: { args: ["recover", "input.mcap", "-o", "recovered.mcap"] },
    knownDifference: {
      id: "recover-library-header",
      summary:
        "Rust recover preserves the source Header.library verbatim; Go recover re-stamps it with the go/mcap writer identity (mcap-go/X.Y.Z).",
      reason:
        "Header.library identifies the software that produced the data, which for a single-input transform like recover is still the original recorder. Rust preserves it verbatim, so the value is stable across repeated transforms. Go re-stamps `mcap-go/X.Y.Z` and prepends any earlier, differing library (a dedup guard at writer.go skips an identical one), so across version bumps the field accretes distinct tokens (e.g. `mcap-go/1.9.0; mcap-go/1.8.0`) and stops cleanly identifying the original producer. The TEN_MESSAGES fixture has an empty source library, so Rust writes the empty original while Go writes `mcap-go/X.Y.Z`. (Rust's single-input transforms — filter/compress/decompress/recover/sort — all preserve; merge/convert intentionally stamp the mcap-rust identity since there is no single source library to carry forward.)",
      desiredBehavior:
        "Rust recover should keep preserving the source Header.library verbatim rather than re-stamping it; rewrite provenance, if needed, belongs in a separate record rather than concatenated into the library field.",
      goBehavior: {
        exitCode: 0,
        files: [
          {
            path: "recovered.mcap",
            exists: true,
            mcapSummary: { libraryContains: "mcap-go/" },
          },
        ],
      },
      rustBehavior: {
        exitCode: 0,
        files: [
          {
            path: "recovered.mcap",
            exists: true,
            mcapSummary: { library: "" },
          },
        ],
      },
    },
  },
  {
    id: "known-difference-doctor-reports-all-structural-errors",
    description:
      "Rust doctor reports every structural error on a truncated file; Go doctor stops at the first read failure.",
    tags: ["known-difference", "doctor"],
    setup: [
      { type: "copy", from: TEN_MESSAGES, to: "{caseWorkDir}/truncated.mcap" },
      // Cut mid-chunk so the data section never reaches a clean DataEnd or Footer.
      { type: "truncate", path: "{caseWorkDir}/truncated.mcap", size: 300 },
    ],
    invocation: { args: ["doctor", "truncated.mcap"] },
    knownDifference: {
      id: "doctor-reports-all-structural-errors",
      summary:
        "On a truncated file, Rust doctor reports the read failure plus the missing DataEnd and Footer records on stderr; Go doctor reports only the first read failure on stdout.",
      reason:
        "Rust doctor continues checking structural invariants after a record read failure and emits diagnostics on stderr, so it surfaces the missing DataEnd/Footer records. Go doctor stops at the first failed token read and prints it on stdout.",
      desiredBehavior:
        "Rust doctor should keep reporting all detectable structural errors (and on stderr) rather than stopping at the first failure.",
      goBehavior: {
        exitCode: "nonzero",
        stdout: {
          kind: "matches",
          pattern: "^(?=[\\s\\S]*truncated in chunk)(?![\\s\\S]*Footer)[\\s\\S]*$",
        },
      },
      rustBehavior: {
        exitCode: "nonzero",
        stderr: { kind: "contains", value: "File does not contain a Footer record" },
      },
    },
  },
  // ---------------------------------------------------------------------------
  // Known differences: Go doctor / recover correctness bugs
  // ---------------------------------------------------------------------------
  {
    id: "known-difference-doctor-crash-on-malformed-chunk-index",
    description:
      "Go doctor crashes with SIGSEGV when a ChunkIndex record fails to parse; Rust doctor reports the error and continues.",
    tags: ["known-difference", "doctor"],
    setup: [
      {
        // Minimal MCAP: magic, empty header, data end, a truncated (4-byte)
        // ChunkIndex record that will fail to parse, footer, closing magic.
        type: "writeBytes",
        to: "{caseWorkDir}/malformed.mcap",
        bytes: [
          // Opening magic
          0x89, 0x4d, 0x43, 0x41, 0x50, 0x30, 0x0d, 0x0a,
          // Header (opcode 0x01, length 8): profile="" library=""
          0x01, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
          0x00, 0x00,
          // DataEnd (opcode 0x0F, length 4): crc=0
          0x0f, 0x04, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
          // ChunkIndex (opcode 0x08, length 4): TRUNCATED — only 4 zero bytes
          // instead of the ~72+ bytes needed for a valid ChunkIndex.
          0x08, 0x04, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
          // Footer (opcode 0x02, length 20): summary_start=38, offset_start=0, crc=0
          0x02, 0x14, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x26, 0x00, 0x00, 0x00, 0x00, 0x00,
          0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
          // Closing magic
          0x89, 0x4d, 0x43, 0x41, 0x50, 0x30, 0x0d, 0x0a,
        ],
      },
    ],
    invocation: { args: ["doctor", "malformed.mcap"] },
    knownDifference: {
      id: "doctor-crash-on-malformed-chunk-index",
      summary:
        "Go doctor dereferences a nil parse result when a ChunkIndex record is malformed, causing a SIGSEGV; Rust doctor logs the parse error and continues checking the file.",
      reason:
        "Go doctor logs the parse error but does not skip the current record, so the nil result is dereferenced on the next line (doctor.go:489). This pattern affects every record type in the Go doctor loop. Rust doctor uses Result-based control flow that makes it impossible to use a failed parse result.",
      desiredBehavior:
        "Rust doctor should continue reporting the parse error and any additional structural problems without crashing; the Go crash is a bug.",
      goBehavior: {
        exitCode: 2,
        stdout: { kind: "contains", value: "Failed to parse chunk index" },
      },
      rustBehavior: {
        exitCode: "nonzero",
        stderr: { kind: "contains", value: "Failed to parse top-level record" },
      },
    },
  },
  {
    id: "known-difference-doctor-crash-on-malformed-attachment-index",
    description:
      "Go doctor crashes with SIGSEGV when an AttachmentIndex record fails to parse; Rust doctor reports the error and continues.",
    tags: ["known-difference", "doctor"],
    setup: [
      {
        // Minimal MCAP with a truncated AttachmentIndex record (opcode 0x0A).
        type: "writeBytes",
        to: "{caseWorkDir}/malformed-attachment-index.mcap",
        bytes: [
          // Opening magic
          0x89, 0x4d, 0x43, 0x41, 0x50, 0x30, 0x0d, 0x0a,
          // Header (opcode 0x01, length 8): profile="" library=""
          0x01, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
          0x00, 0x00,
          // DataEnd (opcode 0x0F, length 4): crc=0
          0x0f, 0x04, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
          // AttachmentIndex (opcode 0x0A, length 4): TRUNCATED — only 4 zero
          // bytes instead of the ~50+ bytes needed for a valid AttachmentIndex.
          0x0a, 0x04, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
          // Footer (opcode 0x02, length 20): summary_start=38, offset_start=0, crc=0
          0x02, 0x14, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x26, 0x00, 0x00, 0x00, 0x00, 0x00,
          0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
          // Closing magic
          0x89, 0x4d, 0x43, 0x41, 0x50, 0x30, 0x0d, 0x0a,
        ],
      },
    ],
    invocation: { args: ["doctor", "malformed-attachment-index.mcap"] },
    knownDifference: {
      id: "doctor-crash-on-malformed-attachment-index",
      summary:
        "Go doctor dereferences a nil parse result when an AttachmentIndex record is malformed, causing a SIGSEGV; Rust doctor logs the parse error and continues.",
      reason:
        "Same nil-dereference pattern as the ChunkIndex case: Go logs the error but falls through to use the nil result (doctor.go:498). Rust control flow prevents use of a failed parse result.",
      desiredBehavior:
        "Rust doctor should continue reporting the parse error without crashing; the Go crash is a bug.",
      goBehavior: {
        exitCode: 2,
        stdout: { kind: "contains", value: "Failed to parse attachment index" },
      },
      rustBehavior: {
        exitCode: "nonzero",
        stderr: { kind: "contains", value: "Failed to parse top-level record" },
      },
    },
  },
  {
    id: "known-difference-recover-writer-chunk-index-serialization",
    description:
      "Go mcap writer's WriteChunkIndex may produce internally inconsistent records when MessageIndexOffsets references channels not in the writer's channel list; Rust writer serializes the map atomically with a runtime length assertion.",
    tags: ["known-difference", "recover"],
    // This is a latent correctness bug in the Go writer's WriteChunkIndex method.
    // It declares the message_index_offsets byte length from len(map) but only
    // serializes entries for channels in w.channelIDs. When the map has channels
    // not yet registered, the declared length exceeds written bytes, producing an
    // internally inconsistent record. The Rust writer iterates the BTreeMap
    // directly with an assert_eq! verifying written bytes match.
    //
    // Recovering a valid MCAP and checking the output is valid exercises this path
    // because recover writes chunks via WriteChunkWithIndexes before registering
    // channels, relying on the deferred AddChannel call to catch up. In the Go
    // writer this CAN produce a mismatched ChunkIndex (depending on timing); the
    // Rust writer is structurally immune.
    invocation: {
      args: ["recover", TEN_MESSAGES, "-o", "recovered.mcap", "--compression", "none"],
    },
    comparison: {
      exitCode: 0,
      stdout: { kind: "ignore" },
      stderr: { kind: "ignore" },
      files: [
        {
          path: "recovered.mcap",
          comparator: { kind: "mcap", mode: "content", allowSemanticFallback: true },
        },
      ],
    },
  },
];

export function validateCases(testCases: readonly CliTestCase[]): string[] {
  const errors: string[] = [];
  const ids = new Set<string>();
  const knownDifferenceIds = new Set<string>();
  for (const testCase of testCases) {
    if (ids.has(testCase.id)) {
      errors.push(`duplicate case id '${testCase.id}'`);
    }
    ids.add(testCase.id);
    if (
      testCase.comparison != undefined &&
      testCase.comparison.stdout == undefined &&
      testCase.comparison.stderr == undefined &&
      (testCase.comparison.files?.length ?? 0) === 0
    ) {
      errors.push(
        `case '${testCase.id}' must explicitly compare or ignore stdout/stderr when using a custom comparison`,
      );
    }
    if (testCase.knownDifference != undefined) {
      const known = testCase.knownDifference;
      if (knownDifferenceIds.has(known.id)) {
        errors.push(`duplicate known-difference id '${known.id}'`);
      }
      knownDifferenceIds.add(known.id);
      for (const [field, value] of Object.entries({
        id: known.id,
        summary: known.summary,
        reason: known.reason,
        desiredBehavior: known.desiredBehavior,
      })) {
        if (value.trim().length === 0) {
          errors.push(`known-difference case '${testCase.id}' must provide ${field}`);
        }
      }
      if (known.goBehavior.exitCode == undefined || known.rustBehavior.exitCode == undefined) {
        errors.push(
          `known-difference case '${testCase.id}' must document go and rust exit behavior`,
        );
      }
    }
  }
  return errors;
}
