/* cspell:words flamegraph lz4 multitopic ndjson noetic notbag pprof samply testdata */

import type { CliTestCase } from "./types.ts";

// These fixtures are generated by `yarn test:conformance:generate-inputs`.
// The suffixes encode the record/index features included in each generated file.
const ONE_MESSAGE = "{dataDir}/OneMessage/OneMessage-ch-chx-mx-pad-rch-rsh-st-sum.mcap";
const ONE_SCHEMALESS =
  "{dataDir}/OneSchemalessMessage/OneSchemalessMessage-ch-chx-mx-pad-rch-st.mcap";
const TEN_MESSAGES = "{dataDir}/TenMessages/TenMessages-ch-chx-mx-pad-rch-rsh-st-sum.mcap";
const ONE_ATTACHMENT = "{dataDir}/OneAttachment/OneAttachment-ax-st-sum.mcap";
const ONE_METADATA = "{dataDir}/OneMetadata/OneMetadata-mdx-st-sum.mcap";
const ROS2_EMBEDDED_SCHEMA_DB3 = "{repoRoot}/testdata/db3/talker-iron.db3";
const NOETIC_MULTITOPIC_NONE = "{repoRoot}/testdata/bags/generated/noetic-multitopic-none.bag";
const NOETIC_MULTITOPIC_BZ2 = "{repoRoot}/testdata/bags/generated/noetic-multitopic-bz2.bag";
const NOETIC_MULTITOPIC_LZ4 = "{repoRoot}/testdata/bags/generated/noetic-multitopic-lz4.bag";

const HELP_PATHS = [
  ["add"],
  ["add", "attachment"],
  ["add", "metadata"],
  ["cat"],
  ["compress"],
  ["convert"],
  ["decompress"],
  ["doctor"],
  ["du"],
  ["filter"],
  ["get"],
  ["get", "attachment"],
  ["get", "metadata"],
  ["info"],
  ["list"],
  ["list", "attachments"],
  ["list", "channels"],
  ["list", "chunks"],
  ["list", "metadata"],
  ["list", "schemas"],
  ["merge"],
  ["recover"],
  ["sort"],
] as const;

const EXIT_CODE_ONLY = {
  exitCode: 0,
  stdout: { kind: "ignore" },
  stderr: { kind: "ignore" },
} as const;

const HELP_EXISTS = {
  exitCode: 0,
  stdout: { kind: "nonempty" },
  stderr: { kind: "ignore" },
} as const;

export const cases: CliTestCase[] = [
  {
    id: "root-help-command-list",
    description:
      "Root help advertises the same supported command list, ignoring the Go-only version subcommand.",
    tags: ["surface", "help"],
    invocation: { args: ["--help"] },
    comparison: {
      exitCode: 0,
      stdout: { kind: "command-list", ignoreCommands: ["version"] },
      stderr: { kind: "text" },
    },
  },
  ...HELP_PATHS.map<CliTestCase>((args) => ({
    id: `command-help-${args.join("-")}`,
    description: `Both CLIs expose help for '${args.join(" ")}'.`,
    tags: ["surface", "help"],
    invocation: { args: [...args, "--help"] },
    comparison: HELP_EXISTS,
  })),
  {
    id: "completion-command",
    description: "Both CLIs generate a shell completion script for a requested shell.",
    tags: ["surface", "completion"],
    invocation: { args: ["completion", "bash"] },
    comparison: {
      exitCode: 0,
      stdout: { kind: "nonempty" },
      stderr: { kind: "ignore" },
    },
  },
  {
    id: "known-difference-version-flag",
    description: "Rust CLI exposes a --version flag; Go CLI exposes a version subcommand.",
    tags: ["known-difference", "surface", "version"],
    invocation: { args: ["--version"] },
    knownDifference: {
      id: "version-flag",
      summary: "Rust CLI accepts 'mcap --version'; Go CLI only accepts 'mcap version'.",
      reason:
        "Rust CLI intentionally exposes version information through the standard --version flag instead of a dedicated subcommand.",
      desiredBehavior:
        "Rust CLI should continue to support --version; the 'version' subcommand remains Go-only by design.",
      goBehavior: {
        exitCode: "nonzero",
        stderr: { kind: "contains", value: "unknown flag: --version" },
      },
      rustBehavior: {
        exitCode: 0,
        stdout: { kind: "nonempty" },
      },
    },
  },
  {
    id: "cat-one-message",
    description: "Basic cat output matches for an indexed MCAP with one schematized message.",
    tags: ["cat", "stdout"],
    invocation: { args: ["cat", ONE_MESSAGE] },
    comparison: {
      exitCode: 0,
      stdout: { kind: "bytes" },
      stderr: { kind: "text" },
    },
  },
  {
    id: "cat-one-schemaless-message",
    description: "Basic cat output matches for an indexed MCAP with one schemaless message.",
    tags: ["cat", "stdout"],
    invocation: { args: ["cat", ONE_SCHEMALESS] },
    comparison: {
      exitCode: 0,
      stdout: { kind: "bytes" },
      stderr: { kind: "text" },
    },
  },
  {
    id: "cat-topic-filter-includes-matching-topic",
    description: "Cat topic filtering includes messages on requested topics.",
    tags: ["cat", "stdout", "topics"],
    invocation: { args: ["cat", ONE_MESSAGE, "--topics", "example"] },
    comparison: {
      exitCode: 0,
      stdout: { kind: "bytes" },
      stderr: { kind: "text" },
    },
  },
  {
    id: "cat-topic-filter-excludes-missing-topic",
    description: "Cat topic filtering emits no messages when no requested topic matches.",
    tags: ["cat", "stdout", "topics"],
    invocation: { args: ["cat", ONE_MESSAGE, "--topics", "missing"] },
    comparison: {
      exitCode: 0,
      stdout: { kind: "text" },
      stderr: { kind: "text" },
    },
  },
  {
    id: "cat-time-filter-includes-range",
    description: "Cat time filtering includes messages in the requested nanosecond range.",
    tags: ["cat", "stdout", "time"],
    invocation: { args: ["cat", ONE_MESSAGE, "--start-nsecs", "2", "--end-nsecs", "3"] },
    comparison: {
      exitCode: 0,
      stdout: { kind: "bytes" },
      stderr: { kind: "text" },
    },
  },
  {
    id: "cat-time-filter-excludes-out-of-range",
    description: "Cat time filtering emits no messages outside the requested range.",
    tags: ["cat", "stdout", "time"],
    invocation: { args: ["cat", ONE_MESSAGE, "--start-nsecs", "3"] },
    comparison: {
      exitCode: 0,
      stdout: { kind: "text" },
      stderr: { kind: "text" },
    },
  },
  {
    id: "cat-stdin-one-message",
    description: "Cat reads stdin when no file argument is supplied.",
    tags: ["cat", "stdout", "stdin"],
    invocation: { args: ["cat"], stdin: { path: ONE_MESSAGE } },
    comparison: {
      exitCode: 0,
      stdout: { kind: "bytes" },
      stderr: { kind: "text" },
    },
  },
  {
    id: "cat-json-unsupported-schema-errors",
    description:
      "Cat --json accepts the flag and errors consistently for unsupported schema encodings.",
    tags: ["cat", "json"],
    invocation: { args: ["cat", ONE_MESSAGE, "--json"] },
    comparison: {
      exitCode: "same",
      stdout: { kind: "text" },
      stderr: { kind: "ignore" },
    },
  },
  {
    id: "cat-json-protobuf-stdin",
    description:
      "Cat --json emits protobuf messages as NDJSON with Go-compatible field casing and zero-value omission.",
    tags: ["cat", "json", "protobuf", "stdin"],
    setup: [
      {
        type: "writeProtobufJsonMcap",
        to: "{caseWorkDir}/protobuf.mcap",
        messages: [
          {
            sequence: 1,
            logTime: 2,
            publishTime: 1,
            snakeCase: "hello",
            zeroValue: 0,
            count: 7,
          },
          {
            sequence: 2,
            logTime: 3,
            publishTime: 2,
            snakeCase: "world",
            zeroValue: 0,
            count: 8,
          },
        ],
      },
    ],
    invocation: { args: ["cat", "--json"], stdin: { path: "{caseWorkDir}/protobuf.mcap" } },
    comparison: {
      exitCode: 0,
      stdout: { kind: "ndjson" },
      stderr: { kind: "text" },
    },
  },
  {
    id: "cat-json-ros1msg-stdin",
    description:
      "Cat --json emits ROS1 messages as NDJSON with Go-compatible nested message, special float, duration, and array output.",
    tags: ["cat", "json", "ros1msg", "stdin"],
    setup: [
      {
        type: "writeRos1JsonMcap",
        to: "{caseWorkDir}/ros1.mcap",
        messages: [
          {
            sequence: 1,
            logTime: 2,
            publishTime: 1,
            headerSeq: 7,
            stampSec: 1,
            stampNsec: 2,
            frameId: "map",
            durationSec: 4,
            durationNsec: 5,
            values: [10, 20],
          },
          {
            sequence: 2,
            logTime: 3,
            publishTime: 2,
            headerSeq: 8,
            stampSec: 2,
            stampNsec: 3,
            frameId: "odom",
            durationSec: 5,
            durationNsec: 6,
            values: [30],
          },
        ],
      },
    ],
    invocation: { args: ["cat", "--json"], stdin: { path: "{caseWorkDir}/ros1.mcap" } },
    comparison: {
      exitCode: 0,
      stdout: { kind: "ndjson" },
      stderr: { kind: "text" },
    },
  },
  {
    id: "info-one-message",
    description: "Info output reports the same stable summary fields for a representative MCAP.",
    tags: ["info", "stdout"],
    invocation: { args: ["info", ONE_MESSAGE] },
    comparison: {
      exitCode: 0,
      stdout: { kind: "info" },
      stderr: { kind: "text" },
    },
  },
  {
    id: "list-channels",
    description: "Channel listing contains the same table data despite formatter differences.",
    tags: ["list", "table"],
    invocation: { args: ["list", "channels", ONE_MESSAGE] },
    comparison: {
      exitCode: 0,
      stdout: { kind: "table" },
      stderr: { kind: "text" },
    },
  },
  {
    id: "list-chunks",
    description: "Chunk listing contains the same table data despite formatter differences.",
    tags: ["list", "table", "chunks"],
    invocation: { args: ["list", "chunks", ONE_MESSAGE] },
    comparison: {
      exitCode: 0,
      stdout: { kind: "table" },
      stderr: { kind: "text" },
    },
  },
  {
    id: "list-schemas",
    description: "Schema listing contains the same table data despite formatter differences.",
    tags: ["list", "table", "schemas"],
    invocation: { args: ["list", "schemas", ONE_MESSAGE] },
    comparison: {
      exitCode: 0,
      stdout: { kind: "table" },
      stderr: { kind: "text" },
    },
  },
  {
    id: "list-metadata",
    description: "Metadata listing contains the same table data despite formatter differences.",
    tags: ["list", "table", "metadata"],
    invocation: { args: ["list", "metadata", ONE_METADATA] },
    comparison: {
      exitCode: 0,
      stdout: { kind: "table" },
      stderr: { kind: "text" },
    },
  },
  {
    id: "list-attachments",
    description: "Attachment listing contains the same table data despite formatter differences.",
    tags: ["list", "table", "attachments"],
    invocation: { args: ["list", "attachments", ONE_ATTACHMENT] },
    comparison: {
      exitCode: 0,
      stdout: { kind: "table" },
      stderr: { kind: "text" },
    },
  },
  {
    id: "get-metadata-json",
    description: "Metadata extraction returns the same JSON object.",
    tags: ["get", "metadata", "json"],
    invocation: { args: ["get", "metadata", ONE_METADATA, "--name", "myMetadata"] },
    comparison: {
      exitCode: 0,
      stdout: { kind: "json" },
      stderr: { kind: "text" },
    },
  },
  {
    id: "get-attachment-by-name",
    description: "Attachment extraction by name writes identical payload bytes.",
    tags: ["get", "attachments", "bytes"],
    invocation: {
      args: ["get", "attachment", ONE_ATTACHMENT, "--name", "myFile", "-o", "attachment.bin"],
    },
    comparison: {
      exitCode: 0,
      stdout: { kind: "text" },
      stderr: { kind: "text" },
      files: [{ path: "attachment.bin", comparator: { kind: "bytes" } }],
    },
  },
  {
    id: "get-attachment-by-offset",
    description: "Attachment extraction by record offset writes identical payload bytes.",
    tags: ["get", "attachments", "bytes", "offset"],
    invocation: {
      args: [
        "get",
        "attachment",
        ONE_ATTACHMENT,
        "--name",
        "myFile",
        "--offset",
        // 8-byte magic + 1-byte header opcode + 8-byte header length + two empty MCAP strings.
        "25",
        "-o",
        "attachment.bin",
      ],
    },
    comparison: {
      exitCode: 0,
      stdout: { kind: "text" },
      stderr: { kind: "text" },
      files: [{ path: "attachment.bin", comparator: { kind: "bytes" } }],
    },
  },
  {
    id: "doctor-valid-file-exits-successfully",
    description:
      "Doctor accepts a representative valid MCAP; warning stream differences are covered separately.",
    tags: ["doctor"],
    invocation: { args: ["doctor", ONE_MESSAGE] },
    comparison: EXIT_CODE_ONLY,
  },
  {
    id: "doctor-strict-message-order-detects-out-of-order-log-time",
    description: "Doctor strict message ordering rejects messages whose log times move backward.",
    tags: ["doctor", "strict-message-order"],
    setup: [
      {
        type: "writeProtobufJsonMcap",
        to: "{caseWorkDir}/out-of-order.mcap",
        chunkedMessages: true,
        messages: [
          {
            sequence: 1,
            logTime: 3,
            publishTime: 1,
            snakeCase: "later",
            count: 1,
          },
          {
            sequence: 2,
            logTime: 2,
            publishTime: 2,
            snakeCase: "earlier",
            count: 2,
          },
        ],
      },
    ],
    invocation: { args: ["doctor", "--strict-message-order", "out-of-order.mcap"] },
    comparison: {
      exitCode: 1,
      stdout: { kind: "ignore" },
      stderr: { kind: "ignore" },
    },
  },
  ...[
    {
      id: "convert-noetic-ros1-bag-none",
      fixture: NOETIC_MULTITOPIC_NONE,
      description: "Converting a Noetic ROS1 bag with uncompressed chunks preserves messages.",
      tags: ["convert", "ros1", "mcap-output"],
    },
    {
      id: "convert-noetic-ros1-bag-bz2",
      fixture: NOETIC_MULTITOPIC_BZ2,
      description: "Converting a Noetic ROS1 bag with bz2 chunks preserves messages.",
      tags: ["convert", "ros1", "mcap-output", "bz2"],
    },
    {
      id: "convert-noetic-ros1-bag-lz4",
      fixture: NOETIC_MULTITOPIC_LZ4,
      description: "Converting a Noetic ROS1 bag with lz4 chunks preserves messages.",
      tags: ["convert", "ros1", "mcap-output", "lz4"],
    },
  ].map<CliTestCase>((testCase) => ({
    id: testCase.id,
    description: testCase.description,
    tags: testCase.tags,
    invocation: {
      args: [
        "convert",
        testCase.fixture,
        "converted.mcap",
        "--compression",
        "none",
        "--include-crc=false",
      ],
    },
    comparison: {
      exitCode: 0,
      stdout: { kind: "ignore" },
      stderr: { kind: "ignore" },
      files: [
        {
          path: "converted.mcap",
          comparator: { kind: "mcap", mode: "content", allowSemanticFallback: true },
        },
      ],
    },
  })),
  {
    id: "filter-topic-output-messages",
    description: "Filtering by topic preserves the same message stream.",
    tags: ["filter", "mcap-output"],
    invocation: {
      args: [
        "filter",
        TEN_MESSAGES,
        "-o",
        "filtered.mcap",
        "-y",
        "example",
        "--output-compression",
        "none",
      ],
    },
    comparison: {
      exitCode: 0,
      stdout: { kind: "text" },
      stderr: { kind: "text", collapseWhitespace: true },
      files: [
        {
          path: "filtered.mcap",
          comparator: { kind: "mcap", mode: "content", allowSemanticFallback: true },
        },
      ],
    },
  },
  {
    id: "filter-exclude-topic-output-messages",
    description: "Filtering with an exclude topic regex removes matching messages from output.",
    tags: ["known-difference", "filter", "mcap-output", "topics"],
    invocation: {
      args: [
        "filter",
        TEN_MESSAGES,
        "-o",
        "filtered.mcap",
        "-n",
        "example",
        "--output-compression",
        "none",
      ],
    },
    knownDifference: {
      id: "filter-exclude-topic-regex",
      summary:
        "Rust filter excludes matching topics with -n/--exclude-topic-regex; Go currently leaves matching messages in place.",
      reason:
        "The Rust CLI applies exclude regexes when rewriting the MCAP, while the legacy Go CLI's current output for this fixture still contains the excluded topic.",
      desiredBehavior:
        "Both CLIs should remove messages whose topics match -n/--exclude-topic-regex before Rust CLI v1.0.",
      goBehavior: {
        exitCode: 0,
        files: [
          {
            path: "filtered.mcap",
            exists: true,
            mcapSummary: { messageCount: 10, channelCount: 1, schemaCount: 1 },
          },
        ],
      },
      rustBehavior: {
        exitCode: 0,
        files: [
          {
            path: "filtered.mcap",
            exists: true,
            mcapSummary: { messageCount: 0, channelCount: 0, schemaCount: 0 },
          },
        ],
      },
    },
  },
  {
    id: "filter-rfc3339-time-range-output-messages",
    description: "Filtering with RFC3339 start/end bounds preserves the same message stream.",
    tags: ["filter", "mcap-output", "time"],
    invocation: {
      args: [
        "filter",
        ONE_MESSAGE,
        "-o",
        "filtered.mcap",
        "-S",
        "1970-01-01T00:00:00.000000002Z",
        "-E",
        "1970-01-01T00:00:00.000000003Z",
        "--output-compression",
        "none",
      ],
    },
    comparison: {
      exitCode: 0,
      stdout: { kind: "text" },
      stderr: { kind: "text", collapseWhitespace: true },
      files: [
        {
          path: "filtered.mcap",
          comparator: { kind: "mcap", mode: "content", allowSemanticFallback: true },
        },
      ],
    },
  },
  {
    id: "filter-includes-metadata-and-attachments",
    description: "Filtering with metadata and attachment flags preserves non-message records.",
    tags: ["filter", "mcap-output", "metadata", "attachments"],
    setup: [
      {
        type: "writeProtobufJsonMcap",
        to: "{caseWorkDir}/content.mcap",
        messages: [
          {
            sequence: 1,
            logTime: 2,
            publishTime: 1,
            snakeCase: "hello",
            count: 7,
          },
        ],
        metadata: [{ name: "cli-conformance", metadata: { key: "value" } }],
        attachments: [
          {
            name: "payload.bin",
            mediaType: "application/octet-stream",
            logTime: 4,
            createTime: 3,
            data: [1, 1, 2, 3, 5, 8],
          },
        ],
      },
    ],
    invocation: {
      args: [
        "filter",
        "content.mcap",
        "-o",
        "filtered.mcap",
        "--include-metadata",
        "--include-attachments",
        "--output-compression",
        "none",
      ],
    },
    comparison: {
      exitCode: 0,
      stdout: { kind: "text" },
      stderr: { kind: "text", collapseWhitespace: true },
      files: [
        {
          path: "filtered.mcap",
          comparator: { kind: "mcap", mode: "content", allowSemanticFallback: true },
        },
      ],
    },
  },
  {
    id: "compress-none-output-messages",
    description: "Rewriting an MCAP with no output compression preserves the same message stream.",
    tags: ["compress", "mcap-output"],
    invocation: {
      args: ["compress", TEN_MESSAGES, "-o", "compressed.mcap", "--compression", "none"],
    },
    comparison: {
      exitCode: 0,
      stdout: { kind: "text" },
      stderr: { kind: "text", collapseWhitespace: true },
      files: [
        {
          path: "compressed.mcap",
          comparator: { kind: "mcap", mode: "content", allowSemanticFallback: true },
        },
      ],
    },
  },
  {
    id: "compress-lz4-output-messages",
    description: "Rewriting an MCAP with lz4 compression preserves the same message stream.",
    tags: ["compress", "mcap-output", "lz4"],
    invocation: {
      args: ["compress", TEN_MESSAGES, "-o", "compressed-lz4.mcap", "--compression", "lz4"],
    },
    comparison: {
      exitCode: 0,
      stdout: { kind: "text" },
      stderr: { kind: "text", collapseWhitespace: true },
      files: [
        {
          path: "compressed-lz4.mcap",
          comparator: { kind: "mcap", mode: "content", allowSemanticFallback: true },
        },
      ],
    },
  },
  {
    id: "compress-zstd-output-messages",
    description: "Rewriting an MCAP with zstd compression preserves the same message stream.",
    tags: ["compress", "mcap-output", "zstd"],
    invocation: {
      args: ["compress", TEN_MESSAGES, "-o", "compressed-zstd.mcap", "--compression", "zstd"],
    },
    comparison: {
      exitCode: 0,
      stdout: { kind: "text" },
      stderr: { kind: "text", collapseWhitespace: true },
      files: [
        {
          path: "compressed-zstd.mcap",
          comparator: { kind: "mcap", mode: "content", allowSemanticFallback: true },
        },
      ],
    },
  },
  {
    id: "compress-unchunked-output-content",
    description: "Rewriting an MCAP with unchunked output preserves content.",
    tags: ["compress", "mcap-output", "unchunked"],
    invocation: {
      args: ["compress", TEN_MESSAGES, "-o", "compressed-unchunked.mcap", "--unchunked"],
    },
    comparison: {
      exitCode: 0,
      stdout: { kind: "text" },
      stderr: { kind: "text", collapseWhitespace: true },
      files: [
        {
          path: "compressed-unchunked.mcap",
          comparator: { kind: "mcap", mode: "content", allowSemanticFallback: true },
        },
      ],
    },
  },
  {
    id: "decompress-output-messages",
    description: "Decompressing an MCAP preserves the same message stream.",
    tags: ["decompress", "mcap-output"],
    invocation: {
      args: ["decompress", TEN_MESSAGES, "-o", "decompressed.mcap"],
    },
    comparison: {
      exitCode: 0,
      stdout: { kind: "text" },
      stderr: { kind: "text", collapseWhitespace: true },
      files: [
        {
          path: "decompressed.mcap",
          comparator: { kind: "mcap", mode: "content", allowSemanticFallback: true },
        },
      ],
    },
  },
  {
    id: "sort-output-messages",
    description: "Sorting an indexed MCAP preserves the same message stream.",
    tags: ["sort", "mcap-output"],
    invocation: {
      args: ["sort", TEN_MESSAGES, "-o", "sorted.mcap"],
    },
    comparison: {
      exitCode: 0,
      stdout: { kind: "text" },
      stderr: { kind: "text", collapseWhitespace: true },
      files: [
        {
          path: "sorted.mcap",
          comparator: { kind: "mcap", mode: "content", allowSemanticFallback: true },
        },
      ],
    },
  },
  {
    id: "merge-output-messages",
    description: "Merging multiple MCAP files preserves the same combined message stream.",
    tags: ["merge", "mcap-output"],
    invocation: {
      args: ["merge", ONE_MESSAGE, ONE_SCHEMALESS, "-o", "merged.mcap", "--compression", "none"],
    },
    comparison: {
      exitCode: 0,
      stdout: { kind: "text" },
      stderr: { kind: "text", collapseWhitespace: true },
      files: [
        {
          path: "merged.mcap",
          comparator: { kind: "mcap", mode: "content", allowSemanticFallback: true },
        },
      ],
    },
  },
  {
    id: "merge-coalesce-channels-none-output-messages",
    description:
      "Merging with channel coalescing disabled preserves the same combined message stream.",
    tags: ["merge", "mcap-output", "coalesce-channels"],
    invocation: {
      args: [
        "merge",
        ONE_MESSAGE,
        ONE_MESSAGE,
        "-o",
        "merged-no-coalesce.mcap",
        "--compression",
        "none",
        "--coalesce-channels",
        "none",
      ],
    },
    comparison: {
      exitCode: 0,
      stdout: { kind: "text" },
      stderr: { kind: "text", collapseWhitespace: true },
      files: [
        {
          path: "merged-no-coalesce.mcap",
          comparator: { kind: "mcap", mode: "content", allowSemanticFallback: true },
        },
      ],
    },
  },
  {
    id: "recover-valid-output-messages",
    description: "Recovering a valid MCAP preserves the same message stream.",
    tags: ["recover", "mcap-output"],
    invocation: {
      args: ["recover", TEN_MESSAGES, "-o", "recovered.mcap", "--compression", "none"],
    },
    comparison: {
      exitCode: 0,
      stdout: { kind: "text" },
      stderr: { kind: "text", collapseWhitespace: true },
      files: [
        {
          path: "recovered.mcap",
          comparator: { kind: "mcap", mode: "content", allowSemanticFallback: true },
        },
      ],
    },
  },
  {
    id: "add-metadata-mutates-file-content",
    description: "Adding deterministic metadata produces equivalent message and metadata content.",
    tags: ["add", "metadata", "mcap-output"],
    setup: [{ type: "copy", from: TEN_MESSAGES, to: "{caseWorkDir}/input.mcap" }],
    invocation: {
      args: ["add", "metadata", "input.mcap", "--name", "cli-conformance", "-k", "key=value"],
    },
    comparison: {
      exitCode: 0,
      stdout: { kind: "text" },
      stderr: { kind: "text", collapseWhitespace: true },
      files: [
        {
          path: "input.mcap",
          comparator: { kind: "mcap", mode: "content", allowSemanticFallback: true },
        },
      ],
    },
  },
  {
    id: "add-attachment-mutates-file-content",
    description:
      "Adding a deterministic attachment produces equivalent message and attachment content.",
    tags: ["add", "attachments", "mcap-output"],
    setup: [
      { type: "copy", from: TEN_MESSAGES, to: "{caseWorkDir}/input.mcap" },
      { type: "writeBytes", to: "{caseWorkDir}/payload.bin", bytes: [1, 1, 2, 3, 5, 8] },
    ],
    invocation: {
      args: [
        "add",
        "attachment",
        "input.mcap",
        "-f",
        "payload.bin",
        "-n",
        "payload.bin",
        "--log-time",
        "42",
        "--creation-time",
        "24",
      ],
    },
    comparison: {
      exitCode: 0,
      stdout: { kind: "text" },
      stderr: { kind: "text", collapseWhitespace: true },
      files: [
        {
          path: "input.mcap",
          comparator: { kind: "mcap", mode: "content", allowSemanticFallback: true },
        },
      ],
    },
  },
  {
    id: "known-difference-recover-lossy-exit-code",
    description:
      "On a truncated MCAP, Rust recover exits 3 (recovered but lossy); Go recover exits 0.",
    tags: ["known-difference", "recover"],
    setup: [
      { type: "copy", from: TEN_MESSAGES, to: "{caseWorkDir}/truncated.mcap" },
      // Cut mid-chunk so only some of the messages are recovered and the data section never
      // reaches a clean DataEnd (TEN_MESSAGES is ~1083 bytes; the chunk spans past byte 300).
      { type: "truncate", path: "{caseWorkDir}/truncated.mcap", size: 300 },
    ],
    invocation: { args: ["recover", "truncated.mcap", "-o", "recovered.mcap"] },
    knownDifference: {
      id: "recover-lossy-exit-code",
      summary:
        "Rust recover exits non-zero (3) when recovery is lossy; Go recover exits 0 once recovery starts.",
      reason:
        "Rust recover signals data loss through the exit code (0 = clean, 1 = nothing recovered, 3 = recovered but lossy) so a partial salvage is not silently reported as success. Go recover returns success on any started recovery, including truncated input.",
      desiredBehavior:
        "Rust recover should exit 3 when one or more messages/records are discarded or the input is truncated mid-record; a clean recovery exits 0 and nothing-recovered exits 1.",
      goBehavior: {
        exitCode: 0,
        files: [{ path: "recovered.mcap", exists: true }],
      },
      rustBehavior: {
        exitCode: 3,
        files: [{ path: "recovered.mcap", exists: true }],
      },
    },
  },
  {
    id: "known-difference-recover-always-decode-chunk-flag",
    description:
      "Go recover accepts --always-decode-chunk; Rust recover removed the flag because it always decodes and re-encodes chunks.",
    tags: ["known-difference", "recover", "surface"],
    invocation: {
      args: ["recover", TEN_MESSAGES, "-o", "recovered.mcap", "--always-decode-chunk"],
    },
    knownDifference: {
      id: "recover-always-decode-chunk-flag",
      summary: "Go recover accepts an --always-decode-chunk flag; Rust recover does not expose it.",
      reason:
        "Rust recover always decodes and validates every chunk and re-encodes records through the writer, so a decode toggle is unnecessary; the --compression flag alone selects the output codec. Rust recover also guarantees a valid, readable output and defaults to --compression preserve, whereas Go copies chunk bytes through verbatim and defaults to zstd.",
      desiredBehavior:
        "Rust recover should keep decoding chunks unconditionally; the --always-decode-chunk flag remains Go-only.",
      goBehavior: {
        exitCode: 0,
        files: [{ path: "recovered.mcap", exists: true }],
      },
      rustBehavior: {
        exitCode: "nonzero",
        stderr: { kind: "contains", value: "--always-decode-chunk" },
      },
    },
  },
  {
    id: "known-difference-version-subcommand",
    description: "Go CLI exposes a 'version' subcommand; Rust CLI only exposes the --version flag.",
    tags: ["known-difference", "surface", "version"],
    invocation: { args: ["version"] },
    knownDifference: {
      id: "version-subcommand",
      summary:
        "Go CLI accepts 'mcap version' as a subcommand; Rust CLI only supports 'mcap --version'.",
      reason:
        "Rust CLI intentionally exposes version information through the standard --version flag instead of a dedicated subcommand.",
      desiredBehavior:
        "Rust CLI should continue to support --version; the 'version' subcommand remains Go-only by design.",
      goBehavior: {
        exitCode: 0,
        stdout: { kind: "anything" },
      },
      rustBehavior: {
        exitCode: "nonzero",
        stderr: { kind: "contains", value: "unrecognized" },
      },
    },
  },
  {
    id: "known-difference-convert-ros2-ament-help",
    description:
      "Go CLI exposes ament-based ROS 2 db3 conversion; Rust CLI intentionally supports embedded-schema db3 conversion instead.",
    tags: ["known-difference", "convert", "surface"],
    invocation: { args: ["convert", "--help"] },
    knownDifference: {
      id: "convert-ros2-ament-help",
      summary:
        "Go convert exposes --ament-prefix-path for ROS 2 db3 conversion; Rust convert does not.",
      reason:
        "Rust convert avoids brittle ament workspace lookup and only converts ROS 2 db3 bags that contain embedded message definitions.",
      desiredBehavior:
        "Rust convert should continue to document the embedded-schema-only behavior for ROS 2 db3 conversion.",
      goBehavior: {
        exitCode: 0,
        stdout: { kind: "contains", value: "--ament-prefix-path" },
      },
      rustBehavior: {
        exitCode: 0,
        stdout: { kind: "matches", pattern: "^(?![\\s\\S]*ament-prefix-path)[\\s\\S]*$" },
      },
    },
  },
  {
    id: "known-difference-convert-ros2-db3-embedded-schemas",
    description:
      "Rust converts self-contained ROS 2 db3 bags with embedded schemas; Go requires ament schemas.",
    tags: ["known-difference", "convert", "ros2"],
    invocation: {
      args: ["convert", ROS2_EMBEDDED_SCHEMA_DB3, "converted.mcap", "--compression", "none"],
      // Make Go's ament-only schema lookup deterministic even when the developer shell has
      // sourced a ROS 2 workspace. Rust does not consult this environment variable.
      env: { AMENT_PREFIX_PATH: "" },
    },
    knownDifference: {
      id: "convert-ros2-db3-embedded-schemas",
      summary:
        "Rust convert reads embedded ROS 2 db3 schemas, while Go convert ignores them and requires ament lookup.",
      reason:
        "The Rust replacement intentionally supports self-contained db3 conversion and omits brittle ament lookup; the legacy Go converter predates embedded db3 schemas.",
      desiredBehavior:
        "Rust convert should continue to convert self-contained ROS 2 db3 bags without requiring a ROS workspace.",
      goBehavior: {
        exitCode: "nonzero",
        stderr: { kind: "contains", value: "schema not found" },
      },
      rustBehavior: {
        exitCode: 0,
        files: [
          {
            path: "converted.mcap",
            exists: true,
            mcapSummary: { profile: "ros2", messageCount: 20, channelCount: 3, schemaCount: 3 },
          },
        ],
      },
    },
  },
  {
    id: "known-difference-convert-extension-dispatch",
    description:
      "Rust convert dispatches by input extension; Go convert dispatches by magic bytes.",
    tags: ["known-difference", "convert", "surface"],
    setup: [{ type: "copy", from: NOETIC_MULTITOPIC_NONE, to: "{caseWorkDir}/input.notbag" }],
    invocation: {
      args: ["convert", "input.notbag", "converted.mcap", "--compression", "none"],
    },
    knownDifference: {
      id: "convert-extension-dispatch",
      summary:
        "Go convert accepts supported inputs with non-standard extensions by magic bytes; Rust convert requires known extensions.",
      reason:
        "Rust convert uses a central extension-to-converter mapping so converters own format validation after dispatch.",
      desiredBehavior:
        "Rust convert should keep extension-based dispatch unless a future CLI design adds explicit input-format selection.",
      goBehavior: {
        exitCode: 0,
        files: [
          {
            path: "converted.mcap",
            exists: true,
            mcapSummary: { profile: "ros1", messageCount: 3, channelCount: 2, schemaCount: 2 },
          },
        ],
      },
      rustBehavior: {
        exitCode: "nonzero",
        stderr: { kind: "contains", value: "unsupported input file extension" },
      },
    },
  },
  {
    id: "known-difference-convert-bool-space-values",
    description:
      "Convert rejects space-separated explicit bool values with implementation-specific parse errors.",
    tags: ["known-difference", "convert", "surface"],
    invocation: {
      args: ["convert", NOETIC_MULTITOPIC_NONE, "converted.mcap", "--include-crc", "false"],
    },
    knownDifference: {
      id: "convert-bool-space-values",
      summary:
        "Go and Rust both reject 'convert --include-crc false', but report different parse failures.",
      reason:
        "The Rust CLI requires explicit bool values to use the '--flag=<value>' form, while the Go CLI's Cobra parser leaves the trailing value as an extra positional argument for this command.",
      desiredBehavior:
        "Keep requiring '--include-crc=false' for explicit Rust bool values unless the CLI parser policy changes before v1.0.",
      goBehavior: {
        exitCode: 1,
        stderr: { kind: "contains", value: "accepts 2 arg(s), received 3" },
      },
      rustBehavior: {
        exitCode: 2,
        stderr: { kind: "contains", value: "unexpected argument 'false'" },
      },
    },
  },
  {
    id: "known-difference-pprof-profile-global",
    description:
      "Go CLI writes pprof profiles; Rust CLI intentionally does not expose --pprof-profile.",
    tags: ["known-difference", "global-options"],
    invocation: { args: ["--pprof-profile", "info", ONE_MESSAGE] },
    knownDifference: {
      id: "global-pprof-profile",
      summary:
        "Go CLI implements --pprof-profile; the Rust CLI intentionally omits the flag and rejects it as an unknown argument.",
      reason:
        "The Go flag is built on Go's runtime/pprof profiler and emits Go-pprof-format artifacts that have no equivalent in Rust. Profiling Rust builds is done with external tooling (for example perf, cargo flamegraph, or samply) rather than a baked-in flag, so the Rust CLI deliberately does not carry it.",
      desiredBehavior:
        "Rust CLI should not expose --pprof-profile; the flag remains Go-only by design.",
      goBehavior: {
        exitCode: 0,
        files: [
          { path: "mcap-cpu.prof", exists: true },
          { path: "mcap-mem.prof", exists: true },
          { path: "mcap-block.pprof", exists: true },
        ],
      },
      rustBehavior: {
        exitCode: 2,
        stderr: { kind: "contains", value: "unexpected argument '--pprof-profile'" },
      },
    },
  },
  {
    id: "known-difference-du-record-accounting",
    description: "Go and Rust currently account for top-level record bytes differently in du.",
    tags: ["known-difference", "du"],
    invocation: { args: ["du", ONE_MESSAGE] },
    knownDifference: {
      id: "du-record-accounting",
      summary: "Go and Rust du currently report different top-level record byte counts.",
      reason:
        "The Rust CLI includes record envelope bytes consistently; the Go CLI reports smaller top-level record byte counts.",
      desiredBehavior:
        "Decide and document the intended accounting model, then make both CLIs report the same values.",
      goBehavior: {
        exitCode: 0,
        stdout: { kind: "contains", value: "chunk         \t155" },
      },
      rustBehavior: {
        exitCode: 0,
        stdout: { kind: "contains", value: "chunk         \t164" },
      },
    },
  },
  {
    id: "known-difference-doctor-warning-stream",
    description: "Doctor warning output currently goes to different streams.",
    tags: ["known-difference", "doctor"],
    invocation: { args: ["doctor", ONE_MESSAGE] },
    knownDifference: {
      id: "doctor-warning-stream",
      summary:
        "Go doctor prints a header-library warning to stdout; Rust doctor prints it to stderr.",
      reason: "Doctor output streams have not been aligned between the two CLIs.",
      desiredBehavior: "Warnings should use the same stream in both CLIs before v1.0.",
      goBehavior: {
        exitCode: 0,
        stdout: { kind: "contains", value: "Header.library" },
      },
      rustBehavior: {
        exitCode: 0,
        stderr: { kind: "contains", value: "Header.library" },
      },
    },
  },
  {
    id: "known-difference-config-global",
    description: "Go CLI accepts a config file; Rust CLI intentionally does not expose --config.",
    tags: ["known-difference", "global-options"],
    setup: [{ type: "writeText", to: "{caseWorkDir}/config.yaml", contents: "{}\n" }],
    invocation: { args: ["--config", "{caseWorkDir}/config.yaml", "info", ONE_MESSAGE] },
    knownDifference: {
      id: "global-config",
      summary:
        "Go CLI accepts --config; the Rust CLI intentionally omits the flag and rejects it as an unknown argument.",
      reason:
        "Go's --config loads a YAML file through viper and prints a confirmation line, but no Go command ever reads a value from it (there are no viper.Get* call sites), so the flag is effectively a no-op. Rather than reproduce a no-op flag, the Rust CLI deliberately omits --config until a real configuration system is designed for both CLIs.",
      desiredBehavior:
        "Rust CLI should not expose --config unless a future, intentionally designed configuration system is added to both CLIs.",
      goBehavior: {
        exitCode: 0,
        stderr: { kind: "contains", value: "Using config file:" },
      },
      rustBehavior: {
        exitCode: 2,
        stderr: { kind: "contains", value: "unexpected argument '--config'" },
      },
    },
  },
];

export function validateCases(testCases: readonly CliTestCase[]): string[] {
  const errors: string[] = [];
  const ids = new Set<string>();
  const knownDifferenceIds = new Set<string>();
  for (const testCase of testCases) {
    if (ids.has(testCase.id)) {
      errors.push(`duplicate case id '${testCase.id}'`);
    }
    ids.add(testCase.id);
    if (
      testCase.comparison != undefined &&
      testCase.comparison.stdout == undefined &&
      testCase.comparison.stderr == undefined &&
      (testCase.comparison.files?.length ?? 0) === 0
    ) {
      errors.push(
        `case '${testCase.id}' must explicitly compare or ignore stdout/stderr when using a custom comparison`,
      );
    }
    if (testCase.knownDifference != undefined) {
      const known = testCase.knownDifference;
      if (knownDifferenceIds.has(known.id)) {
        errors.push(`duplicate known-difference id '${known.id}'`);
      }
      knownDifferenceIds.add(known.id);
      for (const [field, value] of Object.entries({
        id: known.id,
        summary: known.summary,
        reason: known.reason,
        desiredBehavior: known.desiredBehavior,
      })) {
        if (value.trim().length === 0) {
          errors.push(`known-difference case '${testCase.id}' must provide ${field}`);
        }
      }
      if (known.goBehavior.exitCode == undefined || known.rustBehavior.exitCode == undefined) {
        errors.push(
          `known-difference case '${testCase.id}' must document go and rust exit behavior`,
        );
      }
    }
  }
  return errors;
}
