#!/usr/bin/env bash

set -e

conan config init

pushd examples/protobuf_pointcloud_writer
mkdir -p autogenerated
protoc --proto_path=proto --cpp_out=autogenerated proto/foxglove/*.proto
protoc --proto_path=proto --descriptor_set_out=pointcloud_descriptor.pb proto/foxglove/PointCloud.proto
xxd -i pointcloud_descriptor.pb autogenerated/pointcloud_descriptor.pb.h
popd

conan editable add ./mcap mcap/0.1.1
conan install bench --install-folder bench/build/Release \
  -s compiler.cppstd=17 -s build_type=Release --build missing
conan install examples --install-folder examples/build/Release \
  -s compiler.cppstd=17 -s build_type=Release --build missing
conan install test --install-folder test/build/Debug \
  -s compiler.cppstd=17 -s build_type=Debug --build missing

conan build examples --build-folder examples/build/Release
conan build bench --build-folder bench/build/Release
conan build test --build-folder test/build/Debug
