services:
  base:
    build:
      context: .
      dockerfile: dev.Dockerfile
      target: base

  build:
    build:
      context: .
      dockerfile: dev.Dockerfile
      target: build

  bench:
    build:
      context: .
      dockerfile: dev.Dockerfile
      target: bench

  bag2mcap:
    build:
      context: .
      dockerfile: dev.Dockerfile
      target: bag2mcap
