test:
	make -C libmcap test
	make -C ros test
	make -C conformance test

lint:
	make -C libmcap lint
	make -C ros lint
	make -C mcap lint

build-conformance-check:
	make -C conformance build

bench:
	make -C libmcap bench
