# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: complex_message.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15\x63omplex_message.proto\"0\n\x0e\x43omplexMessage\x12\x0e\n\x06\x66ieldA\x18\x01 \x01(\t\x12\x0e\n\x06\x66ieldB\x18\x02 \x01(\tb\x06proto3')



_COMPLEXMESSAGE = DESCRIPTOR.message_types_by_name['ComplexMessage']
ComplexMessage = _reflection.GeneratedProtocolMessageType('ComplexMessage', (_message.Message,), {
  'DESCRIPTOR' : _COMPLEXMESSAGE,
  '__module__' : 'complex_message_pb2'
  # @@protoc_insertion_point(class_scope:ComplexMessage)
  })
_sym_db.RegisterMessage(ComplexMessage)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _COMPLEXMESSAGE._serialized_start=25
  _COMPLEXMESSAGE._serialized_end=73
# @@protoc_insertion_point(module_scope)
