// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const navigation = {
  guidesSidebar: [{ type: "autogenerated", dirName: "guides" }],
  specSidebar: [{ type: "autogenerated", dirName: "spec" }],
  referenceSidebar: [
    "reference/index",
    {
      type: "link",
      label: "C++",
      href: "https://mcap.dev/docs/cpp/",
    },
    {
      type: "link",
      label: "Go",
      href: "https://pkg.go.dev/github.com/foxglove/mcap/go/mcap",
    },
    {
      type: "link",
      label: "Python",
      href: "https://mcap.dev/docs/python/",
    },
    {
      type: "link",
      label: "Rust",
      href: "https://docs.rs/mcap/",
    },
    {
      type: "link",
      label: "Swift",
      href: "https://mcap.dev/docs/swift/documentation/mcap/",
    },
    {
      type: "link",
      label: "TypeScript",
      href: "https://mcap.dev/docs/typescript/",
    },
  ],
};

module.exports = navigation;
