# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: simple_message.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14simple_message.proto\"\x1d\n\rSimpleMessage\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\tb\x06proto3')



_SIMPLEMESSAGE = DESCRIPTOR.message_types_by_name['SimpleMessage']
SimpleMessage = _reflection.GeneratedProtocolMessageType('SimpleMessage', (_message.Message,), {
  'DESCRIPTOR' : _SIMPLEMESSAGE,
  '__module__' : 'simple_message_pb2'
  # @@protoc_insertion_point(class_scope:SimpleMessage)
  })
_sym_db.RegisterMessage(SimpleMessage)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _SIMPLEMESSAGE._serialized_start=24
  _SIMPLEMESSAGE._serialized_end=53
# @@protoc_insertion_point(module_scope)
